### ISSUE TITLE
Communicate Channel?

### ISSUE THREAD

**Issue by StaringTheWorldAtMyRearView123** [vfsfitvnm/frida-il2cpp-bridge#1]
Hi there, I really like this project, is there a discussion channel opening?

**Comment by vfsfitvnm** [comment]
Hi, no there isn't. Why do you think there should be one?

**Comment by StaringTheWorldAtMyRearView123** [comment]
cuz it could gather people easily so we can share thoughts and brainstorming.

**Comment by vfsfitvnm** [comment]
There are already plenty of blogs/tutorials/communities/channels about Frida and RE.
Sure, a channel could be useful to enhance this module specifically, but I don't feel it's necessary: there's nothing "yet to be discovered" about Il2Cpp. Also, anyone can contribute, as they would contribute to any open source project.

However, if you think an important feature is missing, please open an issue about that.

**Comment by StaringTheWorldAtMyRearView123** [comment]
could you share some communities/channels about Frida/RE/Il2cpp to me?
