### ISSUE TITLE
High level backtrace

### ISSUE THREAD

**Issue by zbx911** [vfsfitvnm/frida-il2cpp-bridge#10]
能不能添加个函数，可以回溯c#的堆栈？

**Comment by zbx911** [comment]
```ts
function hook_class_method(method:any,class_name:string,method_name:string) {
    method.intercept({
        // @ts-ignore
       onEnter(instance, parameters) {
            // var tb = Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join("\t\n");
            // console.log(tb)
            var index=0;
            let method_name=method.name
            this.info="[C] call func: "+class_name+"."+method_name+"()"+"\n" //这里存在bug method.name 无法回调
            // console.log("[C] call func:",class_name+"."+method_name+"()")
            for (var parameter of parameters) {
                  // @ts-ignore
                 index=index+1
                 this.info=this.info+"arg"+index+" |"+parameter.value+"|\n"
                 this.info=this.info+"arg"+index+" |"+bin2hex(parameter.value)+"|\n"
                 // console.log("arg"+index,parameter.value);
            }

        },
        // @ts-ignore
        onLeave(returnValue) {


            // this.info=this.info+"return ["+returnValue.class.type.name+"] = "+returnValue.value+"\n"
            this.info=this.info+"ret  |"+returnValue.value+"|\n"
            // if(typeof returnValue.value === 'string')
            {
                  this.info=this.info+"retbs|"+bin2hex(returnValue.value)+"|\n"
            }

            console.log(this.info);
            // console.log("return",returnValue.value);
        }
    });
}
```
如果添加堆栈回溯，只能回溯frida-server.so的调用,需要回溯C#的调用堆栈

**Comment by vfsfitvnm** [comment]
@zbx911 
This is a missing feature. I already tried to implement a traceback system, but I never succeeded.

As a workaround, you could:
- Dump the application
- Disassemble `libil2cpp.so` and rename functions in ida/ghidra
- Use frida's `Thread.backtrace` and insert the virtual addresses in ghidra to see the functions

But a proper traceback system is absolutely needed.

(please use english!)

**Comment by zbx911** [comment]
> 
> 
> @zbx911
> This is a missing feature. I already tried to implement a traceback system, but I never succeeded.
> 
> As a workaround, you could:
> 
>     * Dump the application
> 
>     * Disassemble `libil2cpp.so` and rename functions in ida/ghidra
> 
>     * Use frida's `Thread.backtrace` and insert the virtual addresses in ghidra to see the functions
> 
> 
> But a proper traceback system is absolutely needed.
> 
> (please use english!)

谢谢，你的建议，我已经在使用了。可能是因为il2cpp无调试信息，回溯堆栈失败。

**Comment by zbx911** [comment]
> 
> 
> @zbx911
> This is a missing feature. I already tried to implement a traceback system, but I never succeeded.
> 
> As a workaround, you could:
> 
>     * Dump the application
> 
>     * Disassemble `libil2cpp.so` and rename functions in ida/ghidra
> 
>     * Use frida's `Thread.backtrace` and insert the virtual addresses in ghidra to see the functions
> 
> 
> But a proper traceback system is absolutely needed.
> 
> (please use english!)

Use frida's Thread.backtrace and insert the virtual addresses in ghidra to see the functions
是否可以增加method的属性内存地址？可以方便frida native hook。

**Comment by vfsfitvnm** [comment]
@zbx911
> 是否可以增加method的属性内存地址？可以方便frida native hook。

What do you mean? I don't get how "increasing the memory address" would help!

**Comment by zbx911** [comment]
> 
> 
> @zbx911
> 
> > 是否可以增加method的属性内存地址？可以方便frida native hook。
> 
> What do you mean? I don't get how "increasing the memory address" would help!

提供method在内存的加载地址，方便 frida hook，
例如:
var method_addr= method.address  ;
    Interceptor.attach(method_addr, {
        onEnter: function (args) {
        },
        onLeave: function (retval) {
        }
    })

**Comment by vfsfitvnm** [comment]
@zbx911 
You can get the address of any method (if not generic / not abstract) using the `actualPointer` getter (`Il2Cpp.Method.actualPointer`): https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/index.ts#L288.

However, `Il2Cpp.Method.intercept` is basically a wrapper around frida's `Interceptor.attach`

**Comment by zbx911** [comment]
> 
> 
> @zbx911
> You can get the address of any method (if not generic / not abstract) using the `actualPointer` getter (`Il2Cpp.Method.actualPointer`): https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/index.ts#L288.
> 
> However, `Il2Cpp.Method.intercept` is basically a wrapper around frida's `Interceptor.attach`

ok，thanks for your answer！

**Comment by zbx911** [comment]
trace(): void {
        if (this.actualPointer.isNull()) {
            warn(`Can't trace method ${this.name} from ${this.class.type.name}: pointer is NULL.`);
        }
        try {
            Interceptor.attach(this.actualPointer, () => inform(`${this.relativePointerAsString} ${this.name}`));
        } catch (e) {
            warn(`Can't trace method ${this.name} from ${this.class.type.name}: ${e.message}.`);
        }
    }

===================>>>>>>>>>>>>>>>>>>>


    trace(): void {
        if (this.actualPointer.isNull()) {
            warn(`Can't trace method ${this.name} from ${this.class.type.name}: pointer is NULL.`);
        }
        try {

            Interceptor.attach(this.actualPointer, () =>{ var tb = Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join("\t\n");
            inform(`${this.relativePointerAsString}  $ {tb } ${this.name}`)  } );
        } catch (e) {
            warn(`Can't trace method ${this.name} from ${this.class.type.name}: ${e.message}.`);
        }
    }

**Comment by vfsfitvnm** [comment]
@zbx911 
Yup I could probably improve tracing, gonna do that in few days.

**Comment by zbx911** [comment]
> 
> 
> @zbx911
> Yup I could probably improve tracing, gonna do that in few days.

Come on！

**Comment by vfsfitvnm** [comment]
Hi, I added a `Il2Cpp.Tracer` to partially address this. I guess providing a higher level backtracing (other than frida's) is not possible (?).

**Comment by reitowo** [comment]
Why it is not possible to print a backtrace/stacktrace? Since you can retrieve the address from Thread.backtrace, and we have base address of libil2cpp.so, also we have all relative address to all symbols, I think it is possible to print a beautiful backtrace with il2cpp symbols?

**Comment by vfsfitvnm** [comment]
We need to somehow determine the code size of each method first. In fact, the backtracer won't return the base address of the method (of course), so me must have some way to associate a given address to a method.

I see three options:

1) I remember seeing this information in a (debug) `libil2cpp.so` few months back. However, I don't know if that's the case for every application/version/os.
2)  Sort all the methods by their base addresses and then determine the code size of a method by subtracting its base address from the base address of the next method in the list (but I think it may be imprecise). 
3) Backwards-parse the instructions until a function prologue is detected to determine the base address of that function.

As you can see, all these three paths need investigation.

**Comment by reitowo** [comment]
I think option 2 is reasonable, as many debugger works like this (gdb, lldb....) It will show the offset to the closest symbol.

Most important, it should cover 99% use cases.

**Comment by vfsfitvnm** [comment]
Yeah. Unfortunately I don't know when I will have the time to work on that, however I'll leave this open as a reminder

**Comment by reitowo** [comment]
Take your time ^_^ Not urgent.

**Comment by vfsfitvnm** [comment]
I implemented it and used it with two applications; and my final answer is this feature requires more investigation; at the current state it provides little to no value, honestly.

Frida's `Thread.backtrace` only provides the last 16 call sites (unless you recompile Frida), and it isn't helpful at all considering how much convoluted the Unity call system is. A lot of reflection is involved, and thus those 16 slots get immediately clobbered with useless data.

That's not a complete dealbreaker, however.

Another thing we must sort out is the actual API.

The cleanest solution is to make `this` (which is `Il2Cpp.Class | Il2Cpp.Object` now) something like `(Il2Cpp.Class | Il2Cpp.Object) & { backtrace(): void }`:
```ts
MyClass.method("MyMethod").implementation = function (...args: any[]) {
    this.backtrace();
    return this.method("MyMethod").invoke(args);
};
```

However, perhaps something like this is preferable:
```ts
const bt = MyClass.method("MyMethod").backtrace();
// later on, if required
bt.stop();
```

Or, I could just create a `Il2Cpp.Backtracer` (similar to `Il2Cpp.Tracer`):
```ts
Il2Cpp.backtrace()
    .distinct() // do not re-print if the call stack is identical to the previous one(s)
    .classes(MyClass)
    .and()
    .attach();
```

I prefer the third solution. However, alternatives or other suggestions/ideas are welcomed :)

**Comment by reitowo** [comment]
What I really want (and most encountered situation) is backtracing a method that being called via interface, which is not so easy to statically analyze. And I think third solution is my prefer.

However, if we can start a PR on frida and make the backtrace function accept an parameter to control the depth of tracing, it will be much useful.

**Comment by vfsfitvnm** [comment]
I just added a primitive implementation of `Il2Cpp.Backtracer`. I'd like to collect some feedback before polishing the code and publish a new release.

It works the same as `Il2Cpp.Tracer`, however there is some extra setup needed:
```ts
Il2Cpp.backtrace()
    .fuzzy() // Determines the type of the backtrace (https://frida.re/docs/javascript-api/#thread). Can be either fuzzy or accurate
    .verbose() // Determine whether print duplicate outputs (i.e. if a function is called frequently, you won't see the spam). Can be either verbose (always print) or distinct (do not print duplicates)
    .clean() // Determines whether retain every trace (i.e. if there's a likely-to-be-wrong trace, it won't be printed). Can be either clean (only show reliable method calls) or dirty (show everything)
    .methods(...) // same as Il2Cpp.Tracer
    .and()
    .attach()
```

A *sad* thing is that the backtracer has to collect every `Il2Cpp.Method` to work. This operation may be very slow. I probably need to use a `CModule` or whatever...

**Comment by vfsfitvnm** [comment]
Oh, I forgot to mention that I'm going to add `.verbose()` and `.distinct()` to `Il2Cpp.Tracer` as well to avoid spam (addresses #27 )!

**Comment by Chensem** [comment]
update the npm ?

**Comment by chensem** [comment]
> We need to somehow determine the code size of each method first. In fact, the backtracer won't return the base address of the method (of course), so me must have some way to associate a given address to a method.
> 
> I see three options:
> 
> 1. I remember seeing this information in a (debug) `libil2cpp.so` few months back. However, I don't know if that's the case for every application/version/os.
> 2. Sort all the methods by their base addresses and then determine the code size of a method by subtracting its base address from the base address of the next method in the list (but I think it may be imprecise).
> 3. Backwards-parse the instructions until a function prologue is detected to determine the base address of that function.
> 
> As you can see, all these three paths need investigation.

I think the idea is right , some days before , i also do some investigation about il2cpp backtracer , and found this article , [il2cpp internal](https://zhuanlan.zhihu.com/p/132717069) , when il2cpp throws a exception , the backtrace will generate more detailed imformation about symbols , so when we opened Il2Cpp.installExceptionListener , the detailed backtrace information we can see , the article explains the il2cpp game will have a segement named il2cpp , the backtracer via dichotomy to determine the closer symbol .

**Comment by chensem** [comment]
https://git.kpi.fei.tuke.sk/tg206vc/liveitprojects/-/blob/283bff797d9dc1cf3ae0b5bc12830233b3c19250/Il2CppOutputProject/IL2CPP/libil2cpp/vm-utils/NativeSymbol.cpp#L145

**Comment by vfsfitvnm** [comment]
I don't know how I could use such information (in practice); I already played with `StackTrace::WalkStack`, but it's no different than Frida's `Thread.backtrace`...

**Comment by reitowo** [comment]
Is it possible to get the stacktrace by manually create an il2cpp Exception?

**Comment by vfsfitvnm** [comment]
@cnSchwarzer Yeah, but it's empty!

**Comment by vfsfitvnm** [comment]
Implemented in `0.8.0` (there's a huge room for improvement by the way...)

**Comment by shalzuth** [comment]
FYI - it is alot easier to just do `mscorlib.class("System.Environment").method("get_StackTrace").invoke()`

**Comment by vfsfitvnm** [comment]
@shalzuth 
Does it work for you?
I couldn't find a way to get the stack trace using the C# api, it was always empty

**Comment by shalzuth** [comment]
Yes it does work - this is a working example:
```js
assembly_csharp.class("Client.Rpc.Core.Implementation.RpcClient").method("SendRequest").implementation =
    function(v1,v2,v3,v4,v5,v6) {
        console.log('SendRequest : ' + v1);
        console.log(mscorlib.class("System.Environment").method("get_StackTrace").invoke());
        this.method("SendRequest").invoke(v1,v2,v3,v4,v5,v6);
    };```

**Comment by vfsfitvnm** [comment]
Hmm, the following snippet:
```ts
Il2Cpp.perform(() => {
    const get_StackTrace = Il2Cpp.corlib.class("System.Environment").method("get_StackTrace");
    const Parse = Il2Cpp.corlib.class("System.Boolean").method("Parse");

    Parse.implementation = function (...args) {
        const retval = Parse.invoke(...args);
        console.log(get_StackTrace.invoke());
        return retval;
    }

    Parse.invoke(Il2Cpp.string("False"));
});
```
outputs:
```
"  at System.Environment.get_StackTrace () <0x00000 + 0xffffffff> 0 in <00000000000000000000000000000000>:0 "
```

But `System.Boolean::Parse` is supposed to invoke `System.Boolean::TryParse`...
Relying on Frida's `Thread::backtrace`:
```ts
Il2Cpp.backtrace().thread(Il2Cpp.currentThread!).classes(Parse.class).and().attach();
```
 gives the expected result:
```
il2cpp: 
0x00996650+0x000 System.Boolean::Parse

il2cpp: 
0x00996750+0x000 System.Boolean::TryParse
0x00996650+0x060 System.Boolean::Parse
```

**Comment by shalzuth** [comment]
Hmm interesting - it seems if the invoker starts from Frida, the Environment.StackTrace is just the single stack line.
If the invoker is from the Unity game thread, it works.
