### ISSUE TITLE
Accessing 0x10 Error while invoke non static method

### ISSUE THREAD

**Issue by dvgmdvgm** [vfsfitvnm/frida-il2cpp-bridge#101]
Hello. First of all big thanks for A12 fix.

I want to invoke some method but it's non static.
try to invoke like that : 
```
const classs = Il2Cpp.Domain.assembly("imageName").image.class("className");
classs.method<void>("MethodName").invoke((Il2Cpp.String.from("data"));
```

it gives me this output : 
`Error: access violation accessing 0x10
    at invokeRaw (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:168)`

My class have Instance object too.
Maybe i should to invoke my method with Instance object?
How i can achieve it?
Thank you.

**Comment by vfsfitvnm** [comment]
That's a static method, otherwise you would get [another](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/method.ts#L195) error.
Also, it doesn't look like a `frida-il2cpp-bridge` issue, however I cannot give you more info since you didn't provide the signature of the method you are trying to invoke

**Comment by dvgmdvgm** [comment]
@vfsfitvnm i also get this error that you show to me serveral tries before.
`must be invoked throught a Il2Cpp.Object, not a Il2Cpp.Class`
How it can be resolved?
Sorry for distrubing

**Comment by vfsfitvnm** [comment]
You must call that method using a `Il2Cpp.Object`.  E.g:
```cs
class System.String
{
    System.Boolean Contains(System.String value); // 0x0082c664;
    static System.Boolean IsNullOrEmpty(System.String value); // 0x0082c684;
}
```
```ts
const SystemString = Il2Cpp.Image.corlib.class("System.String");
const string = Il2Cpp.String.from("hello");

// Contains is not static, so:
console.log(string.object.method<boolean>("Contains").invoke(Il2Cpp.String.from("el"))); // true

// IsNullOrEmpty is static, so:
console.log(SystemString.method<boolean>("IsNullOrEmpty").invoke(string)); // true
```
The difference is in how you obtain the method: `Contains` is obtained via a `Il2Cpp.Object` (`Il2Cpp.String::object` returns a `Il2Cpp.Object`), `IsNullOrEmpty` is obtained via a `Il2Cpp.Class`.

I don't know how you can retrieve an instance of that class, it really depends on what you are trying to do. You can take a look at the past issues (like #39)

**Comment by dvgmdvgm** [comment]
It's all about corlib...
But how about Assembly-CSharp?
Try by this snippet :

```const SystemObject = Il2Cpp.Image.corlib.class("System.Object");

const PerformanceManager = Il2Cpp.Domain.assembly("Assembly-CSharp").image.class("PerformanceManager");

const Infl = PerformanceManager.inflate(SystemObject);

const Instance = Infl.new();

log(Instance);

Instance.method("DataLoaded").invoke(get_grapgicsProfile("MIN"));


OUTPUT : 
`il2cpp: cannot inflate class PerformanceManager: it has no generic parameters`

**Comment by vfsfitvnm** [comment]
Well it seems there's a bit of confusion here... Why are you trying to inflate a generic class?

Also, did you read the issue I linked?
