### ISSUE TITLE
Doesn't recognize second .ctor

### ISSUE THREAD

**Issue by dvgmdvgm** [vfsfitvnm/frida-il2cpp-bridge#103]
Hello.
In previous builds we can implement/invoke secont .ctor
first : `.ctor`
second : `.ctor_`

But on latest version i get this output when try to implement second constructor
`il2cpp: couldn't find method .ctor_ in ClassName, did you mean .ctor?`

My code : 
```
mod("Assembly-CSharp-firstpass", "My.ClassName").method<void>(".ctor_").implementation = function (byteStr) {
        log("DATA = ", String.fromCharCode(...byteStr));
        this.method<void>(".ctor_").invoke(byteStr);
    };
```

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Snippets#overloading

**Comment by dvgmdvgm** [comment]
Now i know that it's called "overload".
Thanks. Works Great
