### ISSUE TITLE
il2cpp: couldn't find existed class

### ISSUE THREAD

**Issue by dvgmdvgm** [vfsfitvnm/frida-il2cpp-bridge#105]
Hey..
Trying to implement method like that : 
```
Il2Cpp.Domain.assembly("Assembly-CSharp").image.class("GameManager.Settings").method<boolean>("isComplete").implementation = function() {
        return true;
    };
```
But have following output : 
`il2cpp: couldn't find class GameManager.Settings in Assembly-CSharp.dll, did you mean Settings?`

But this class 100% in Assembly-CSharp.

**Comment by vfsfitvnm** [comment]
Keep in mind the class name you see in the dump is type name of the class: it also contains outer class names. So, it may be possible (I cannot have this piece of information - I don't have the whole dump) that  `CutsceneManager` in `CutsceneManager.CutsceneSettings` is the outer class name and, by fatality, there's also a class named `CutsceneSettings` in the outer scope:

```cs
class CutsceneManager
{
    class CutsceneSettings
    {
    }
}

class CutsceneSettings
{
}
```

Would you check if this works?
```ts
Il2Cpp.Domain.assembly("Assembly-CSharp").image.class("CutsceneManager").nested("CutsceneSettings")
```

**Comment by dvgmdvgm** [comment]
@vfsfitvnm yes. It's works for me. Thanks a lot!

**Comment by vfsfitvnm** [comment]
Hehe, that got me a couple of times, too!
