### ISSUE TITLE
How to call a method of the parent class instead?

### ISSUE THREAD

**Issue by wildsheepz** [vfsfitvnm/frida-il2cpp-bridge#106]
I have an object instance of RevivePlayerConfirmationMenu and I would like to call IP2Menu.CloseMenu() instead of RevivePlayerConfirmationMenu.CloseMenu(). Is there a way to do this with 0.7.6?
```
// Assembly-CSharp
class Vengeance.Client.IP2Menu : Vengeance.Client.IP2Behaviour
{
    ...
    System.Void CloseMenu(); // 0x0163c760
    ...
}
// Assembly-CSharp
class Vengeance.Client.RevivePlayerConfirmationMenu : Vengeance.Client.IP2Menu
{
    ...
    System.Void CloseMenu(); // 0x00e96578
    ...
}
```

In the meantime, I am using the following code:
```
if (currentMenu.class.type.name == "Vengeance.Client.RevivePlayerConfirmationMenu"){
    var closeFunc = new NativeFunction(AssemblyCSharpImage.class("Vengeance.Client.IP2Menu").method("CloseMenu").virtualAddress, 'void', ['pointer'])
    closeFunc(currentMenu.handle)
}
```

**Comment by kruvcraft21** [comment]
lol, there is an option that this is an overloaded method, then there is no point in calling

**Comment by wildsheepz** [comment]
> lol, there is an option that this is an overloaded method, then there is no point in calling

What do you mean? CloseMenu() is not overloaded, its an overridden method.

**Comment by wildsheepz** [comment]
![image](https://user-images.githubusercontent.com/7615185/154612656-5cb85830-2eb2-42a3-95e3-59a8c59dc373.png)
I would like to skip over some code and call IP2Menu.CloseMenu().

**Comment by kruvcraft21** [comment]
you probably don't quite understand me. in version 0.7.0, the `base` property was removed and it seemed to me quite a logical solution, but you are now demonstrating the opposite situation. Having api 0.7.6, it is probably impossible to call this function, due to the fact that the number of parameters matches, the return type too. You can try calling via the frida api, that is, via `NativeFunction`, then you will have to process the parameters yourself.

**Comment by vfsfitvnm** [comment]
Yup, there no way to do that, but if you really have to:
```ts
const CloseMenu = AssemblyCSharp.class("Vengeance.Client.IP2Menu").method("CloseMenu");
const IP2Menu = (CloseMenu as any).withHolder(currentMenu) as Il2Cpp.Method<void>;

IP2Menu.invoke();
```

However, I could consider making [`withHolder`](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/method.ts#L274) - the method which binds a `Il2Cpp.Method` to a `Il2Cpp.Object` - public

**Comment by wildsheepz** [comment]
Thanks @kruvcraft21 and @vfsfitvnm for you inputs!
