### ISSUE TITLE
 Handle for "Il2CppType" cannot be NULL.

### ISSUE THREAD

**Issue by ngoalong123** [vfsfitvnm/frida-il2cpp-bridge#13]
Hello @vfsfitvnm !
How to fix this error?

`Error: Handle for "Il2CppType" cannot be NULL.
    at raise (/_.js:3496)
    at NativeStructNotNull (/_.js:3617)
    at Il2CppType (/_.js:3023)
    at get type (/_.js:2810)
    at call (native)
    at <anonymous> (/_.js:20)
    at toString (/_.js:2048)
    at dump (/_.js:1645)`

**Comment by vfsfitvnm** [comment]
@ngoalong123 
Hi, this error means you are trying to create a `Il2Cpp.Type` with a `NULL` (`0x0`) pointer. As far as I know `Il2CppType` (same as `Il2CppClass`, `MethodInfo`, `FieldInfo` and so on) cannot be `NULL`.

However, what's the context here?
What are you trying to do?

**Comment by ngoalong123** [comment]
I am trying il2cpp.dump()

Vào 19:09, Th 3, 13 thg 7, 2021 vfsfitvnm ***@***.***> đã
viết:

**Comment by vfsfitvnm** [comment]
@ngoalong123 
Oh, this is interesting.
What's your platform? What's the application you are working on?

**Comment by ngoalong123** [comment]
I fixed that error. Thank you so much 😘😘😘😘

Vào 19:28, Th 3, 13 thg 7, 2021 vfsfitvnm ***@***.***> đã
viết:

**Comment by vfsfitvnm** [comment]
lol
