### ISSUE TITLE
How to specify the unity version

### ISSUE THREAD

**Issue by kruvcraft21** [vfsfitvnm/frida-il2cpp-bridge#135]
using any code, even an empty one, I get this error :`il2cpp: couldn't determine the Unity version, please specify it manually`
how do I specify the version ?

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/96#issuecomment-1042788077

However, what's the app name? Did it work previously?

**Comment by kruvcraft21** [comment]
well, I do not know if this has worked before. This is my fan project (ver. unity 2019.4.16f1). Link to the apk:https://drive.google.com/file/d/1UD9dG6WEH2OZAjE0ppwLyHCgi7pIDLIV/view?usp=sharing.

 If needed , I can provide the source code of this project

**Comment by vfsfitvnm** [comment]
Thanks, not needed.
The link I posted above is the correct solution

**Comment by kruvcraft21** [comment]
okay, I tested it, yes indeed it is a solution option. It turns out we are closing the issue?

**Comment by vfsfitvnm** [comment]
Yup!
