### ISSUE TITLE
how to process ref field

### ISSUE THREAD

**Issue by anonymous5l** [vfsfitvnm/frida-il2cpp-bridge#14]
how to get data value 

i try parse data to `Il2Cpp.Array<number>` but failed

i don't know how to convert that field

```CSharp
public static void EncDecBytes(ref byte[] data, byte[] key) { }
```

**Comment by vfsfitvnm** [comment]
@anonymous5l 
This is a know limitation (already put in in the readme).

I'm not an expert, however reference types should just be wrappers (pointers) to the value, so it should be very easy to handle them: you can treat them like `NativePointers` and then you can just do: `new Il2Cpp.Object(ref.readPointer())` and you should be done.

**Comment by anonymous5l** [comment]
@vfsfitvnm thx i figer it out. 

here is example
```typescript
XOR.methods.EncDecBytes.intercept(    {
        onEnter(instance, parameters) {
            let key = parameters.key.value as Il2Cpp.Array<number>;
            let data = new Il2Cpp.Array<number>(parameters.data.valueHandle.readPointer()); // ref 
...
```

**Comment by vfsfitvnm** [comment]
Yup! This is what I meant.
I'll leave this issue open because this needs to be handled better.

**Comment by vfsfitvnm** [comment]
I added `Il2Cpp.Reference` and `Il2Cpp.Pointer` to handle respectively managed pointers (references, `&`) and unmanaged pointers (raw pointers, `*`).
