### ISSUE TITLE
DUMP  There is no Assembly-CSharp 

### ISSUE THREAD

**Issue by caodocument** [vfsfitvnm/frida-il2cpp-bridge#151]
Il2Cpp.perform(() => {
    Il2Cpp.dump().fileName("dump.cs").classes().build();
}

The Assembly-CSharp class is present in il2cpp.so
but I DUMP  There is no Assembly-CSharp

**Comment by vfsfitvnm** [comment]
Hi, please update `frida-il2cpp-bridge` to the latest version

**Comment by caodocument** [comment]
![image](https://user-images.githubusercontent.com/56826415/158343290-4e34cfe2-4f0b-4df8-9f5c-5d953b5cf04e.png)
Updated to the latest version, it seems still not

**Comment by caodocument** [comment]
![image](https://user-images.githubusercontent.com/56826415/158344593-cd50d5b1-1f42-4d9e-ab92-55688f0045fa.png)

**Comment by caodocument** [comment]
![image](https://user-images.githubusercontent.com/56826415/158346847-cfff5f9c-7273-479a-b90e-14b23f33c362.png)

**Comment by vfsfitvnm** [comment]
Would you try this snippet?

```ts
Il2Cpp.perform(() => {
    console.log(`test 1: ${Il2Cpp.Domain.assemblies.find(assembly => assembly.name == "Assembly-CSharp")?.handle}`);
    console.log(`test 2: ${Il2Cpp.Domain.tryAssembly("Assembly-CSharp")?.handle}`);
});
```

**Comment by caodocument** [comment]
test 1: undefined
test 2: undefined
There is no

**Comment by vfsfitvnm** [comment]
Uhm, what about this one?
```ts
Il2Cpp.perform(() => {
    for (const assemblyObject of Il2Cpp.Domain.object.method<Il2Cpp.Array<Il2Cpp.Object>>("GetAssemblies").overload().invoke()) {
        console.log(assemblyObject);
    }
});
```

**Comment by caodocument** [comment]
Rebuilded
TypeError: not a function

**Comment by caodocument** [comment]
![image](https://user-images.githubusercontent.com/56826415/158377119-6338604a-38ae-4a13-a334-0b81ded98522.png)

**Comment by caodocument** [comment]
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
UnityEngine.SharedInternalsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AssetBundleModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.PhysicsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.SubsystemsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.GridModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.InputLegacyModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestAssetBundleModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.XRModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AndroidJNIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.DirectorModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.InputModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.JSONSerializeModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.ParticleSystemModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.ScreenCaptureModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.TerrainModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.TilemapModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestAudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestTextureModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestWWWModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.VFXModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.VRModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.VideoModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.OdinInspector.Attributes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.Utilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.Serialization.Config, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
CgSdk, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
DOTween, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=null
Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.Serialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Unity.Timeline, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Zenject-usage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Cinemachine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
DOTween43, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
DOTween46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
IFix.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
NGCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
NssPlugins, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
PandoraLogger, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
TencentMapSDK, Version=1.0.6822.29266, Culture=neutral, PublicKeyToken=null
zxing.unity, Version=0.16.6.0, Culture=neutral, PublicKeyToken=null
NssMain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
DOTweenPro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
NGRemoteScene, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
UnityEngine.SharedInternalsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AssetBundleModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.PhysicsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.SubsystemsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.TextRenderingModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.GridModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.IMGUIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.ImageConversionModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.InputLegacyModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.Physics2DModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestAssetBundleModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.XRModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AndroidJNIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.DirectorModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.InputModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.JSONSerializeModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.ParticleSystemModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.ScreenCaptureModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.TerrainModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.TilemapModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UIElementsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestAudioModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestTextureModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.UnityWebRequestWWWModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.VFXModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.VRModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.VideoModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.OdinInspector.Attributes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.Utilities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.Serialization.Config, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
CgSdk, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
DOTween, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=null
Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null
Sirenix.Serialization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Unity.Timeline, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Zenject-usage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Cinemachine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
DOTween43, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
DOTween46, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
IFix.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
NGCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
NssPlugins, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
PandoraLogger, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
TencentMapSDK, Version=1.0.6822.29266, Culture=neutral, PublicKeyToken=null
zxing.unity, Version=0.16.6.0, Culture=neutral, PublicKeyToken=null
NssMain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
DOTweenPro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
NGRemoteScene, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null

**Comment by caodocument** [comment]
ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=null 
Is it in here

**Comment by vfsfitvnm** [comment]
Ok, you got it.
As you can see, there's no `Assembly-CSharp` there: there's nothing I can do about this.

I suspect it has been renamed; however are you sure that assembly exists?

**Comment by caodocument** [comment]
Well~, there's someone out there who has succeeded

**Comment by vfsfitvnm** [comment]
> there's someone out there who has succeeded

What does this mean? You just said `ICSharpCode.SharpZipLib` is the expected assembly.

**Comment by caodocument** [comment]
![image](https://user-images.githubusercontent.com/56826415/158378724-9407d624-c47b-4e4c-9a9b-0c0172f5cd69.png)
Should be and  The same There are hidden

**Comment by vfsfitvnm** [comment]
I miss the point of the discussion... what's the issue?
