### ISSUE TITLE
Failed to load script: timeout was reached ONLY on long operations

### ISSUE THREAD

**Issue by SamueleD78** [vfsfitvnm/frida-il2cpp-bridge#156]
So i've a hook called with all the entries in a dictionary. It's very long, like 4-5 thousands of entry.
It look like this:

```
hook.implementation = function (value: Il2Cpp.Pointer) {
    const internalvalue = inst.method<Il2Cpp.String>("InternalFunc").invoke(value);
    console.log(value, internalvalue);
    return true;
};
```

This way, everything works well.
BUT, when i add a function call to an object, like this:

```
hook.implementation = function (value: Il2Cpp.Pointer) {
    const internalvalue = inst.method<Il2Cpp.String>("InternalFunc").invoke(value);
    const internalobj = new Il2Cpp.Object(value);
    console.log(internalobj.method<Il2Cpp.ValueType>("get_State").invoke(), value, internalvalue);
    return true;
};

```

it does some iteration, a lot of 'em too, like 1000, but a certain point it shows the error `Failed to load script: timeout was reached`.
I've tried to call other function rather than the "get_State" in the example, but the outcome it's always the same, at a certain point it stops with timeout.

If i take away something from the console.log, it starts working, like this:

`console.log(internalobj.method<Il2Cpp.ValueType>("get_State").invoke());` // no timeout

**Comment by SamueleD78** [comment]
Nevermind, it was my problem, cause i had to wrap everyting in a setTimeout, it was a frida related thing, not your library thing.

I'm sorry, and thank you

**Comment by vfsfitvnm** [comment]
@SamueleD78
Yeah, moreover you are using `Il2Cpp.Pointer` incorrectly: it represents pointer types (e.g. `System.Bool *`, `System.Object *`), not a generic memory address. You can directly use `Il2Cpp.Object`:
```ts
hook.implementation = function (value: Il2Cpp.Object) {
    const internalvalue = inst.method<Il2Cpp.String>("InternalFunc").invoke(value);
    console.log(value.method<Il2Cpp.ValueType>("get_State").invoke(), value, internalvalue);
    return true;
};
```
Also, this may happen if `get_State` takes a bit to execute (it also returns a `Il2Cpp.ValueType`, which adds a considerable overhead).

PS - `setTimeout`/`setImmediate` is indeed the correct solution, however keep in mind the callback is executed inside the frida thread instead of the intercepted one.

**Comment by SamueleD78** [comment]
> PS - `setTimeout`/`setImmediate` is indeed the correct solution, however keep in mind the callback is executed inside the frida thread instead of the intercepted one.

Does that mean i cannot access the memory objects?
How it could be bypassed as a problem?

**Comment by SamueleD78** [comment]
I think i understood, i have to wrap it in a Il2Cpp.perform(() => {})

**Comment by vfsfitvnm** [comment]
> Does that mean i cannot access the memory objects?

No, it means you *may* get an access violation error, if you don't get any, you are fine

> How it could be bypassed as a problem?

The proper solution would be avoid any heavy computation; however **the timeout thing is not an error afaik**, you can simply ignore it

> I think i understood, i have to wrap it in a Il2Cpp.perform(() => {})

Nope, `Il2Cpp.perform` won't do anything once you called it once

**Comment by SamueleD78** [comment]
I can't ignore the load timeout, cause it's stopping the script execution at all.
I did it this way:
```
import "frida-il2cpp-bridge";

function myFunc(): void {
    Il2Cpp.perform(() => {
      /*...*/
    });
}

setTimeout(myFunc, 0);
```
If i'm calling my function outside Il2Cpp.perform, i get an access violation.
This way i don't get the access violation nor the timeout, cause the script it's actually loaded according to frida

Thank you for the time you are using for answering me, it's really precious

**Comment by vfsfitvnm** [comment]
Oh you meant wrapping the whole script like that; it's ok then!
