### ISSUE TITLE
Il2Cpp.perform not being called?

### ISSUE THREAD

**Issue by ifoverload** [vfsfitvnm/frida-il2cpp-bridge#158]
Hi!
Why is this perform method seems not called at all?
![code](https://img001.prntscr.com/file/img001/uwjn0mf9QVeLiMpJBQxg3g.png)

Used emulator x86 memu, frida-server also x86
command  "frida -Uf com.unity.games -l _agent.js --no-pause"

The game has Unity version: 2017.4.40f1 is this not supported? (i dont know unity version range)
i've tried to edit that "moduleName" in "Il2CppBase/base.js " to desired il2cpp target.so and auto compile with cmd "npm run watch" because the game load different name
but still not work. thank you :)

**Comment by vfsfitvnm** [comment]
Hi, emulators are problematic; it doesn't work because they use different ways to load a shared library.

However, you could try adding `--realm emulated` to the Frida command and see if it works.

If doesn't I can already tell you there's nothing I can do about this

**Comment by ifoverload** [comment]
> Hi, emulators are problematic; it doesn't work because they use different ways to load a shared library.
> 
> However, you could try adding `--realm emulated` to the Frida command and see if it works.
> 
> If doesn't I can already tell you there's nothing I can do about this

So i ended up trying with my android phone But got the same result.
could be the game has some protection? do i have wrong set-up?
do u have a link to example game working. i just wanted to try
thank you for your quick time :)

**Comment by vfsfitvnm** [comment]
@ifoverload What game did you try?

**Comment by ifoverload** [comment]
> @ifoverload What game did you try?

_seen_ used armeabi-v7a version as always
the game seems to load logic.so from /data/data/com/app_libs as il2cpp library there...

**Comment by vfsfitvnm** [comment]
It looks like that game has a protection - e.g. calling any `il2cpp` api will result in an access violation error. There's nothing I can do about this, unfortunately
