### ISSUE TITLE
The problem with the dump of structures

### ISSUE THREAD

**Issue by kruvcraft21** [vfsfitvnm/frida-il2cpp-bridge#167]
Hi,
After the dump was formed, I decided to work with the structures. In all structures, the field offset does not start from `0x0`, but from `0x10` for `arm64` and `0x8` for `arm`

```cs
// Arm64
// Assembly-CSharp
struct Str : System.ValueType
{
    System.String field1; // 0x10
    System.Int32 field2; // 0x18
}

// Arm
// Assembly-CSharp
struct Str  : System.ValueType
{
    System.String field1; // 0x8
    System.Int32 field2; // 0xc
}
```

it should be like this:

```cs
// Arm64
// Assembly-CSharp
struct Str : System.ValueType
{
    System.String field1; // 0x0
    System.Int32 field2; // 0x8
}

// Arm
// Assembly-CSharp
struct Str  : System.ValueType
{
    System.String field1; // 0x0
    System.Int32 field2; // 0x4
}
```

**Comment by vfsfitvnm** [comment]
Hi, why would you expect these offsets to start from zero? What are the advantages?
`il2cpp` api returns the "wrong" offsets also.

Moreover, structs can be boxed to objects, so I would have to check if a certain object is a boxed struct before retrieving fields: this is certainly uglier than the adopted solution (= always subtract `Il2CppObject` size (16, 8) when it's a `Il2Cpp.ValueType`).

Also, this can't be a "dump only" thing.

**Comment by kruvcraft21** [comment]
okay
