### ISSUE TITLE
error will dumping 

### ISSUE THREAD

**Issue by Luckrat** [vfsfitvnm/frida-il2cpp-bridge#171]
il2cpp: dumping System...
il2cpp: dumping Mono.Security...
il2cpp: dumping System.Core...
il2cpp: dumping UnityEngine...
il2cpp: dumping System.Xml...
il2cpp: dumping UnityEngine.UI...
il2cpp: dumping System.Runtime.Serialization...
il2cpp: dumping sharedRuntime...
il2cpp: dumping ICSharpCode.SharpZipLib...
il2cpp: dumping Newtonsoft.Json...
il2cpp: dumping PlayMaker...
il2cpp: dumping usequencerRuntime...
il2cpp: dumping websocket-sharp...
il2cpp: dumping Assembly-CSharp-firstpass...
TypeError: Cannot read property 'readS32' of undefined
il2cpp: dumping mscorlib...
il2cpp: dumping System...
il2cpp: dumping Mono.Security...
il2cpp: dumping System.Core...
il2cpp: dumping UnityEngine...
il2cpp: dumping System.Xml...
il2cpp: dumping UnityEngine.UI...
il2cpp: dumping System.Runtime.Serialization...
il2cpp: dumping sharedRuntime...
il2cpp: dumping ICSharpCode.SharpZipLib...
il2cpp: dumping Newtonsoft.Json...
il2cpp: dumping PlayMaker...
il2cpp: dumping usequencerRuntime...
il2cpp: dumping websocket-sharp...
il2cpp: dumping Assembly-CSharp-firstpass...
TypeError: Cannot read property 'readS32' of undefined 

after this stuck

**Comment by vfsfitvnm** [comment]
Could you give more context please? (E.g. what's the application)

**Comment by Luckrat** [comment]
It's a android game when I try to dump it's stuck and I got only 1 mb dump only which is useless

**Comment by vfsfitvnm** [comment]
Ok, but what's the game name / identifier?

**Comment by Luckrat** [comment]
Cops

**Comment by vfsfitvnm** [comment]
This is the problematic class:
```c#
enum msg.EServerPkgCmd : System.Enum
{
    System.Int32 value__; // 0x10
    static System.Int32 CS_LOBBY_PLAYER_JOIN_MATCH_NTF = 5002;
    static System.Int32 CS_LOBBY_PLAYER_QUIT_MATCH_NTF = 5004;
    static System.Int32 CS_LOBBY_PLAYER_LOGIN_REQ = 5005;
    // ...
}
```
This `enum` class is strange: its fields type is `System.Int32`, but it "should" be `msg.EServerPkgCmd`. I said _should_ because I don't know if this is due to their Il2Cpp customization or whatsoever.

Btw the fix is easy, I just have to decide how to handle this case

**Comment by vfsfitvnm** [comment]
Fixed in `0.7.11`.
However, as I said in #40, that game is heavily customized / protected, so you'll probably have other errors (`access violation` errors typically).

**Comment by Luckrat** [comment]
one last question there we can dump specific class because game getting shutdow while dumping cant get the class i need name called "..."

**Comment by WimpyMistake** [comment]
@Luckrat this is how I achieved it

```ts
const lib = Il2Cpp.Domain.assembly("GameAssembly").image;
const clazz = lib.class("Game.Namespace.Class");
console.log(clazz);
```
