### ISSUE TITLE
Wrong class reflection

### ISSUE THREAD

**Issue by SamueleD78** [vfsfitvnm/frida-il2cpp-bridge#178]
In a project i'm working on, in the cs dump there is a class with some methods, some static, some not. Something like this:

```
struct Game.SomeStruct {
  void someMethod(); // 0xADDRESS1
  static Game.SomeStruct FromString(System.String id, System.Boolean flag); // 0xADDRESS2
}
```

So invoking the method `FromString` is supposed to give me back a `Game.SomeStruct` object. If i `console.log` the resulting object, it says `Game.SomeStruct` as if it's correct, but I tried to invoke `someMethod` from the resulting object, without result, it says `TypeError: not a function`.

So i watched into IDA the `FromString` function definition at `0xADDRESS2` , and it's totally different, it actually accept only 1 parameter and it gives back a value from an enum instead of pointer to an object.

**Comment by vfsfitvnm** [comment]
> but I tried to invoke someMethod from the resulting object, without result, it says TypeError: not a function.

`Game.SomeStruct` is a `struct` (`Il2Cpp.ValueType`, not a `Il2Cpp.Object`), and structs do not have methods. You need to box it into a `Il2Cpp.Object` first.

> So i watched into IDA the FromString function definition at 0xADDRESS2 , and it's totally different, it actually accept only 1 parameter and it gives back a value from an enum instead of pointer to an object.

Don't expect a 1:1 relationship between Il2Cpp and IDA!

**Comment by SamueleD78** [comment]
i'm sorry, my bad, that was lack of my comprehension. Boxing it made it works, thank you.

About the lack of 1:1 relationship between il2cpp and IDA, that makes me courious.
How it's possible that the methods signatures are different?? (honest question)

**Comment by vfsfitvnm** [comment]
Well, I don't know the correct answer, keep in mind a disassembler may erroneously infer the parameter count or their types. Simple scenario: a il2cpp function takes two parameters, but for some reason the second one is unused. The compilation may erase that parameter completely. At this point, il2cpp still shows 2 parameters, but any disassembler will show just 1.

Also, there are other implementation defined things: in unity versions < 2018.3.0, **every** function requires an instance pointer, so, if a method is static, you must pass NULL as first parameter (https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/method.ts#L203). Il2Cpp does not know this thing, but any disassembler does

**Comment by vfsfitvnm** [comment]
PS: boxing will make a copy
