### ISSUE TITLE
How to invoke a function that requires an Enum?

### ISSUE THREAD

**Issue by comjinz** [vfsfitvnm/frida-il2cpp-bridge#179]
I am not good at English.

```
C# -> void Test(Action callback) 
in frida-> callback.method("Invoke").invoke(); // working
```

```
C# -> void Test(Action<EnumResultType> callback)  ???  
in  frida-> callback.method("Invoke").invoke(1); // not working
----------------------------------------------------
1 == EnumResultType.Success
```
Error Message
TypeError: cannot read property 'message' of null
    at invokeRaw (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:170)
    at <anonymous> (index.ts:49)
    at call (native)
    at callback (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:116)

**Comment by vfsfitvnm** [comment]
You are passing a number (1), but an enum field is not a number, but a value type (well, #171 is an exception). See https://github.com/vfsfitvnm/frida-il2cpp-bridge/discussions/145#discussioncomment-2340877.

However, I must handle this scenario properly and display a decent error message, `cannot read property 'message' of null` is shameful, I apologize

**Comment by comjinz** [comment]
@vfsfitvnm 

It works.
Thank you very much.

**Comment by vfsfitvnm** [comment]
@comjinz 
Uhm, `cannot read property 'message' of null` is a strange one. I don't know why it happens, so I'll just a generic error message...
