### ISSUE TITLE
Il2Cpp.scheduleOnInitializerThread should check whether the current thread id is the main one

### ISSUE THREAD

**Issue by qingpengchen2011** [vfsfitvnm/frida-il2cpp-bridge#180]
I want to delay the execution of my code by settimeout inside the hook fuction. here is my code:

```
const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
const MethodDataGet_UI_Collection = MainMenuSceneType.method<void>("DataGET");
MethodDataGet_UI_Collection.implementation = function (arg) {
    this.method<void>("DataGET").invoke(arg);
    setTimeout(() => {
        Il2Cpp.perform(() => {
            log("++IL2Cpp.perform: SearchForGame");
            const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
            const instant = MainMenuSceneType.field<Il2Cpp.Object>("instance").value.field<Il2Cpp.Object>("searchGameUi").value;
            instant.method<void>("search").invoke(0, NULL, NULL);
        })
    }, 5000);

}
```

And it works if I don't run it inside setTimeout 

```
const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
const MethodDataGet_UI_Collection = MainMenuSceneType.method<void>("DataGET");
MethodDataGet_UI_Collection.implementation = function (arg) {
    this.method<void>("DataGET").invoke(arg);
    log("SearchForGame");
    const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
    const instant = MainMenuSceneType.field<Il2Cpp.Object>("instance").value.field<Il2Cpp.Object>("searchGameUi").value;
    instant.method<void>("search").invoke(0, NULL, NULL);
}
```
The error msg is:
```
{"message":"access violation accessing 0x0","type":"access-violation","address":"0x70192da920","memory":{"operation":"read","address":"0x0"},"context":{"pc":"0x70192da920","sp":"0x707bb64d30","x0":"0x6fb01987f0","x1":"0x0","x2":"0x707bb64dd0","x3":"0x0","x4":"0x1","x5":"0x701993be19","x6":"0x707bb64df0","x7":"0x707bb64d90","x8":"0x0","x9":"0x0","x10":"0x0","x11":"0x0","x12":"0x0","x13":"0x0","x14":"0x0","x15":"0x0","x16":"0x7019c82930","x17":"0x7108512860","x18":"0x0","x19":"0x6f403a5bf0","x20":"0x0","x21":"0x1","x22":"0x707bb68020","x23":"0x0","x24":"0x1","x25":"0x6f403a5de0","x26":"0x0","x27":"0x80","x28":"0x0","fp":"0x0","lr":"0x70192da920"},"nativeContext":"0x0","fileName":"node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js","lineNumber":119}
```

**Comment by vfsfitvnm** [comment]
Hi, all I can think of is the `search` method you are trying to invoke requires some thread specific data the `frida` thread doesn't have. `setTimeout` always schedules the callback on the frida thread (you can verify it yourself with `console.log(Process.getCurrentThreadId())` here and here). That's why it works when you don't wrap it in `setTimeout`: the callback will just execute in the current thread, which is the "main" one for il2cpp.

Instead, you need to use `Il2Cpp.scheduleOnInitializerThread`:
```ts
    setTimeout(() => {
        Il2Cpp.scheduleOnInitializerThread(() => {
            log("++IL2Cpp.scheduleOnInitializerThread: SearchForGame");
            const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
            const instant = MainMenuSceneType.field<Il2Cpp.Object>("instance").value.field<Il2Cpp.Object>("searchGameUi").value;
            instant.method<void>("search").invoke(0, NULL, NULL);
        })
    }, 5000);
```

**However**, there are some quirks you need to know. Please read this: https://github.com/vfsfitvnm/frida-il2cpp-bridge/discussions/145#discussioncomment-2342400

**Comment by qingpengchen2011** [comment]
Hours ago, I've tried to print the thread id and attached threads in the two different location
```

const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
const MethodDataGet_UI_Collection = MainMenuSceneType.method<void>("DataGET");
MethodDataGet_UI_Collection.implementation = function (arg) {
    this.method<void>("DataGET").invoke(arg);

    //Location A:
    const threadId = Il2Cpp.currentThread!!.id
    console.log("main threadId: " + threadId);
    const threads = Il2Cpp.attachedThreads;
    threads.forEach(t => {
        console.log("\t attached thread id: " + t.id);
    })

    setTimeout(() => {
        Il2Cpp.perform(() => {
            //Location B:
            const threadId = Il2Cpp.currentThread!!.id
            log("setTimeout threadId: " + threadId);
            const threads = Il2Cpp.attachedThreads;
            threads.forEach(t => {
                console.log("\t attached thread id: " + t.id);
            })

            const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
            const instant = MainMenuSceneType.field<Il2Cpp.Object>("instance").value.field<Il2Cpp.Object>("searchGameUi").value;
            instant.method<void>("search").invoke(0, NULL, NULL);
        })
    }, 5000);

}
```
In location A:
```
main threadId: 30659
         attached thread id: 30659
         attached thread id: 30721
         attached thread id: 30756
         attached thread id: 30770
         attached thread id: 30771
         attached thread id: 30776
         attached thread id: 30777
         attached thread id: 30780
         attached thread id: 30781
         attached thread id: 30782
```
In location B:
```
setTimeout threadId: 30649
         attached thread id: 30659
         attached thread id: 30721
         attached thread id: 30756
         attached thread id: 30770
         attached thread id: 30771
         attached thread id: 30776
         attached thread id: 30777
         attached thread id: 30780
         attached thread id: 30781
         attached thread id: 30782
         attached thread id: 30649
```
All I do is to verify the setTimeOut thread is attached to the application domain. And I didn't realize the il2cpp "main" thread thing.

**Comment by vfsfitvnm** [comment]
> All I do is to verify the setTimeOut thread is attached to the application domain

This is guaranteed by `Il2Cpp.perform`. However, this is not enough for some methods: you can only call them within the correct thread (`Il2Cpp.attachedThreads[0].id`).

`Il2Cpp.scheduleOnInitializerThread` tries to do that, however the [implementation](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/base.ts#L183) is wobbly and probably won't work. However you get the idea.

Unfortunately, Frida doesn't offer a way to schedule a callback on a given thread (yet), so we can only rely on `Interceptor.attach`.
Moreover, in C# side, I couldn't find a way to schedule a `System.Function` (or whatsoever) on a given `System.Threading.Thread`, but I guess it requires more investigation

**Comment by qingpengchen2011** [comment]
I've tried your solution with printing logs. 
```
    setTimeout(() => {
        log("main threadId " + Process.getCurrentThreadId());
        Il2Cpp.scheduleOnInitializerThread(() => {
            log("++IL2Cpp.scheduleOnInitializerThread: SearchForGame");
            log("\t timeout threadId:" + Process.getCurrentThreadId());
            const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
            const instant = MainMenuSceneType.field<Il2Cpp.Object>("instance").value.field<Il2Cpp.Object>("searchGameUi").value;
            instant.method<void>("search").invoke(0, NULL, NULL);
        })
    }, 5000);

```
Sometimes it works, somethings it doesn't. When it works, the thread id is the same, and vice versa. The behavior is just as you said. 
---

works:
```
2022/05/01 06:20:06:171 main threadId: 4506, Il2CppThread:4506
2022/05/01 06:20:11:178 ++IL2Cpp.scheduleOnInitializerThread: SearchForGame
2022/05/01 06:20:11:179          timeout threadId: 4506, Il2CppThread:4506
```
doesn't work:
```
2022/05/01 06:15:36:494 main threadId 4259
2022/05/01 06:15:41:502 ++IL2Cpp.scheduleOnInitializerThread: SearchForGame
2022/05/01 06:15:41:503          timeout threadId:4367
Error: access violation accessing 0x0
    at invokeRaw (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:119)
    at makeCall_CheckIfCanStartGame (agent/game-api.ts:180)
    at <anonymous> (agent/game-api.ts:144)
    at <anonymous> (node_modules/frida-il2cpp-bridge/dist/il2cpp/base.js:120
```

**Comment by vfsfitvnm** [comment]
Uhm, probably I should check [here](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/base.ts#L186) if the current thread is actually the main one.

Would you use this function, instead of `Il2Cpp.scheduleOnInitializerThread` and see if the behavior is consistent?
```ts
async function scheduleOnInitializerThread<T>(block: () => T | Promise<T>): Promise<T> {
    return new Promise<T>(resolve => {
        const listener = Interceptor.attach(Il2Cpp.Api._threadCurrent, () => {
            if (Il2Cpp.currentThread?.id == Il2Cpp.attachedThreads[0].id) {
                listener.detach();
                const result = block();
                setImmediate(() => resolve(result));
            }
        });
    });
}
```

**Comment by qingpengchen2011** [comment]
> Uhm, probably I should check [here](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/base.ts#L186) if the current thread is actually the main one.
> 
> Would you use this function, instead of `Il2Cpp.scheduleOnInitializerThread` and see if the behavior is consistent?
> 
> ```ts
> async function scheduleOnInitializerThread<T>(block: () => T | Promise<T>): Promise<T> {
>     return new Promise<T>(resolve => {
>         const listener = Interceptor.attach(Il2Cpp.Api._threadCurrent, () => {
>             if (Il2Cpp.currentThread?.id == Il2Cpp.attachedThreads[0].id) {
>                 listener.detach();
>                 const result = block();
>                 setImmediate(() => resolve(result));
>             }
>         });
>     });
> }
> ```

Yes, it works well so far. I'll do more tests and give feedback if any error occurs. I get confused with the **if condition**. ` if (Il2Cpp.currentThread?.id == Il2Cpp.attachedThreads[0].id)` 
Doesn't that mean the callback function we provided to the scheduleOnInitializerThread may not be called if the currentThread id is not the same as the "main" thread id. And As we can see from the log I posted before, the thread id can( or definitely can ) be different sometimes?

**Comment by vfsfitvnm** [comment]
> And As we can see from the log I posted before, the thread id can( or definitely can ) be different sometimes?

Yes, your previous post demonstrated it can be different (I didn't expect that, that's why the `if` check was omitted).

However, I'll see if I can find a more reliable solution (e.g. using C# objects) in the following days; in case of failure, I'll just fix the actual `Il2Cpp.scheduleOnInitializerThread` to include the `if` check

**Comment by qingpengchen2011** [comment]
> > And As we can see from the log I posted before, the thread id can( or definitely can ) be different sometimes?
> 
> Yes, your previous post demonstrated it can be different (I didn't expect that, that's why the `if` check was omitted).
> 
> However, I'll see if I can find a more reliable solution (e.g. using C# objects) in the following days; in case of failure, I'll just fix the actual `Il2Cpp.scheduleOnInitializerThread` to include the `if` check

I do need that delay execution function. Thanks for your great work - really appreciate it.

**Comment by vfsfitvnm** [comment]
> I'll see if I can find a more reliable solution (e.g. using C# objects) in the following days

Found it! Now, the new [implementation](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/thread.ts#L94) is the default one. However, I kept the old one and renamed it to `scheduleOnInitializerThread2`.

#### `scheduleOnInitializerThread`
pros: more reliable
cons: may not work with old/customized unity versions

#### `scheduleOnInitializerThread2`
pros: good last resort, simple implementation
cons: may not work

**Comment by qingpengchen2011** [comment]
> > I'll see if I can find a more reliable solution (e.g. using C# objects) in the following days
> 
> Found it! Now, the new [implementation](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/thread.ts#L94) is the default one. However, I kept the old one and renamed it to `scheduleOnInitializerThread2`.
> 
> #### `scheduleOnInitializerThread`
> pros: more reliable cons: may not work with old/customized unity versions
> 
> #### `scheduleOnInitializerThread2`
> pros: good last resort, simple implementation cons: may not work

Wow, awesome!

**Comment by qingpengchen2011** [comment]
I've tried the two new functions scheduleOnInitializerThread and scheduleOnInitializerThread2.  They don't seem to work in my project. I get unity version: 2020.3.24f1. And I add some logs. It seem that the Il2cppThread.id doesn't seem to work. 

```
class Il2CppThread {
 async schedule(block) {
        (0, console_1.warn)(" in schedule");   // -> print:  in schedule
        const thisThreadId = this.id;
        (0, console_1.warn)("schedule thisThreadId: " + thisThreadId); // ->  print nothing. 
        ..........
       }
}
static async scheduleOnInitializerThread2(block) {
        (0, console_1.warn)(`scheduleOnInitializerThread2`);  //-> print: scheduleOnInitializerThread2
        const threads = this.attachedThreads; 
         (0, console_1.warn)(`threads length: ${threads.length}`); // -> print: threads length: 10
        const targetThreadId = threads[0].id;
        (0, console_1.warn)(`scheduling on thread ${targetThreadId}`); // -> print nothing. 
}
```

And this old one works.
```
async function scheduleOnInitializerThread<T>(block: () => T | Promise<T>): Promise<T> {
    return new Promise<T>(resolve => {
        const listener = Interceptor.attach(Il2Cpp.Api._threadCurrent, () => {
            if (Il2Cpp.currentThread?.id == Il2Cpp.attachedThreads[0].id) {
                listener.detach();
                const result = block();
                setImmediate(() => resolve(result));
            }
        });
    });
}
```

**Comment by qingpengchen2011** [comment]
And I find out that If I wrap the two function in Il2Cpp.perform. They both work well.
works well.
```
      setTimeout(() => {
                Il2Cpp.perform(() => {
                    Il2Cpp.scheduleOnInitializerThread(() => {
                        GameApi.makeCall_searchForGame();
                    });
                });
            }, 5000);
```
doesn't work.
```
            setTimeout(() => {
                Il2Cpp.scheduleOnInitializerThread(() => {
                    GameApi.makeCall_searchForGame();
                });
            }, 5000);
```

**Comment by vfsfitvnm** [comment]
Yeah. You are right. I just realized `il2cpp_thread_get_all_attached_threads` only works if you call if from an attached thread. After 5000ms, the frida thread is not attached anymore and the call fails. Gonna fix it immediately

**Comment by vfsfitvnm** [comment]
@qingpengchen2011 

I reverted version `0.7.12`. `0.7.13` is different and should work now (https://github.com/vfsfitvnm/frida-il2cpp-bridge#0713).
To solve the `il2cpp_thread_get_all_attached_threads` thing, I had to make `Il2Cpp.Thread::schedule` call `setTimeout` itself, so:

```ts
MethodDataGet_UI_Collection.implementation = function (arg) {
    this.method<void>("DataGET").invoke(arg);
    
    Il2Cpp.currentThread?.schedule(() => {
        const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
        const instant = MainMenuSceneType.field<Il2Cpp.Object>("instance").value.field<Il2Cpp.Object>("searchGameUi").value;
        instant.method<void>("search").invoke(0, NULL, NULL);
    }, 5000);
}
```

**Comment by qingpengchen2011** [comment]
> @qingpengchen2011
> 
> I reverted version `0.7.12`. `0.7.13` is different and should work now (https://github.com/vfsfitvnm/frida-il2cpp-bridge#0713). To solve the `il2cpp_thread_get_all_attached_threads` thing, I had to make `Il2Cpp.Thread::schedule` call `setTimeout` itself, so:
> 
> ```ts
> MethodDataGet_UI_Collection.implementation = function (arg) {
>     this.method<void>("DataGET").invoke(arg);
>     
>     Il2Cpp.currentThread?.schedule(() => {
>         const MainMenuSceneType = GameApi.getClass("Assembly-CSharp", "Game.MainMenu.MainMenuScene")
>         const instant = MainMenuSceneType.field<Il2Cpp.Object>("instance").value.field<Il2Cpp.Object>("searchGameUi").value;
>         instant.method<void>("search").invoke(0, NULL, NULL);
>     }, 5000);
> }
> ```

It works, no more erros.
