### ISSUE TITLE
A trailing comma in tsconfig.json

### ISSUE THREAD

**Issue by ChuJiani** [vfsfitvnm/frida-il2cpp-bridge#188]
First, thank you for this wonderful tool! It helps me a lot!

I want to mention an unexpected trailing comma in [tsconfig.json line13](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/b49a0c642d4d741551f700bd55f644d9883e015c/tsconfig.json#L13). It looks like this:
```
{
    ...
    "strict": true,
}
```
When I first tried to compile the script with frida-compile, an error occured about this. I was new to typescript and frida-compile then, and I wondered at first if there were any problems with my environment (without referring to error log carefully, though), which cost me sometime to locate and fix it.

Some json parsers allow for trailing commas indeed, but frida-compile seems unable to handle it correctly, so **removing the comma** may reduce unnecessary doubts in compiling step.

Thank you for you tool again! ( •̀ ω •́ )✧

**Comment by vfsfitvnm** [comment]
`tsc` doesn't complain, and that file is not exposed to `npm`, so I don't really get why someone should use `frida-compile` on the source code - however, I agree that trailing comma should be removed
