### ISSUE TITLE
iOS: cannot detect il2cpp library

### ISSUE THREAD

**Issue by S3eeD2** [vfsfitvnm/frida-il2cpp-bridge#194]
No problem with UnityFramework, but can’t dump Non-UnityFramework "default binaries".

**Comment by vfsfitvnm** [comment]
I apologize but I don't get the problem - I don't have a iOS device... could you elaborate? What are _Non-UnityFramework "default binaries"_?

**Comment by S3eeD2** [comment]
There is 2 types of unity games ,first type default binary (usually named something like the game name) and the other one is UnityFramework with is located in UnityFramework.framework folder.

if its UnityFramework everything work fine, but if the game not have UnityFramework, it stuck forever here->

Spawning `com.thegame.com`...
Rebuilded
Spawned `com.thegame.com`. Resuming main thread!
[Apple iPhone::com.thegame.com]->


my index.ts

```
import "frida-il2cpp-bridge";
console.log("Rebuilded")


Il2Cpp.perform(() => {

    Il2Cpp.dump();	
});
```

**Comment by vfsfitvnm** [comment]
Ok, now I got it. 

I perform that check here: https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/base.ts#L139

But it looks like it fails, e.g. line 140 returns `undefined` instead of the "_Non-UnityFramework default binary_", so it thinks there's UnityFramework. 

Is the "_Non-UnityFramework default binary_" available when the process is created?

Would you spawn the app with the following script?
```ts
console.log(Module.findExportByName(null, "il2cpp_init")):
```

**Comment by S3eeD2** [comment]
spawning the app with this script did nothing (just stuck), but write the script to the console return null.

console.log(Module.findExportByName(null, "il2cpp_init"));
null

**Comment by vfsfitvnm** [comment]
Well, it looks like that binary is loaded dynamically. I don't check for this situation because I don't know what the binary name would be.
Just to be sure, does it work when _attaching_? E.g. let the game load, then attach to it.

**Comment by S3eeD2** [comment]
<let the game load, then attach to it.>
tbh i dont know how to do this

**Comment by vfsfitvnm** [comment]
https://summit-labs.frida.ninja/frida-tool-reference/frida

E.g. launch the app (as you would normally do), then launch frida **without** the spawn flag (`-f`)

**Comment by S3eeD2** [comment]
No problem with that, i can attach to the binary, but if you mean the script it still not work

**Comment by vfsfitvnm** [comment]
Ok, what about the script? Does the dump work?

If so, you could avoid spawing until I find a good solution

**Comment by S3eeD2** [comment]
No, script still not working, anyway thinks for trying, i will be here if you want me to test anything.

**Comment by vfsfitvnm** [comment]
> script still not working

Hmm, that's odd... Are you sure that's a Il2Cpp game / has `il2cpp` exports?

**Comment by S3eeD2** [comment]
> has `il2cpp` exports?

Not sure, but this issue not only with this game, all the games not have UnityFramework.

**Comment by vfsfitvnm** [comment]
What's the game name/id/link to store?

**Comment by S3eeD2** [comment]
_seen_

**Comment by vfsfitvnm** [comment]
Closing as out of scope: that application does not expose Il2Cpp exports somehow, so there's no way I can make it compatible with `frida-il2cpp-bridge`.
