### ISSUE TITLE
How to invoke an instance method

### ISSUE THREAD

**Issue by Abdelrahmanamhawy** [vfsfitvnm/frida-il2cpp-bridge#196]
When I try to invoke a method :

const CSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;
const moneyDroper=CSharp.class("moneyDropper")
const dropMoney=moneyDroper.method("dropMoney").invoke()

I get an error : 
cannot invoke a non-static method dropMoney: must be invoked throught a Il2Cpp.Object, not a Il2Cpp.Class

and when i try to initate an object instead using : 
const object =moneyDroper.new().dropMoney()

i get another error saying : 
TypeError: not a function

And when i try to invoke the method using : 
className.method<void>("dropMoney").invoke();

Failed to load script: script(line 14): SyntaxError: unexpected token in expression: '>'

The class I am trying to hook is that : 
class moneyDropper : UnityEngine.MonoBehaviour
{
    UnityEngine.GameObject[] dropPosition; // 0x18
    UnityEngine.GameObject smallMoneyPrefab; // 0x20
    System.Boolean canDrop; // 0x28
    System.Void dropMoney(); // 0x009e9c44
    System.Void stopDrop(); // 0x009e9cc4
    System.Void invokedDrop(); // 0x009e9c48
    System.Void throwMoney(); // 0x009e9ccc
    System.Void .ctor(); // 0x009e9fcc
}

I am currently trying to attach to the address directly ,but the function might not be called .

**Comment by vfsfitvnm** [comment]
The method you are trying to invoke is not static, hence you need an object in order to call it:
```ts
moneyDroper.new().method("dropMoney").invoke();
```

However this will (probably) have no effect - you are creating a new object that is not part of the game.

So, you need to obtain an existing `moneyDropper` instance.
You can do so by either:
1- Intercepting a method that has a `moneyDropper` as parameter or whose instance is a `moneyDropper` or has a `moneyDropper` field ([wiki](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Snippets#heap-scanning));
2- Scanning the heap to find every `moneyDropper` instance ([wiki](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Snippets#heap-scanning)).

**Comment by Abdelrahmanamhawy** [comment]
Oh okay . Thank you so much 
It gives me a different error  "Abort was called " , but you are right i should try your suggestions .  I tried with the interceptor to attach to the native library and add the offset but no luck . I will read about the heap scanning code and try again with the intereptor .

**Comment by Abdelrahmanamhawy** [comment]
Hi ,sorry for another question . I am running your _.js script instead of the index ,so i put all my code in it .  I currently have a a sytnax error on line ( Il2Cpp.GC.choose(SystemType).forEach((instance: Il2Cpp.Object) => {) it says it is missing a comma . Any idea how to tackle this ? 

Il2Cpp.perform(() => {
    // 모든 dll 파일 덤프 > dump.cs 파일로 추출
    //Il2Cpp.dump();
    //Il2Cpp.dump("DiceClient.dll");
	const CSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;
	const moneyDroper=CSharp.class("moneyDropper")
	//moneyDroper.method("dropMoney").invoke()
	moneyDroper.new().method("dropMoney").invoke();
	
	
    const mscorlib = Il2Cpp.Domain.assembly("mscorlib").image;
    const SystemType = mscorlib.class("System.Type");

    // +++ heap scanning using class descriptors +++
    Il2Cpp.GC.choose(SystemType).forEach((instance: Il2Cpp.Object) => {
        // instance.class.type.name == "System.Type"
		console.log("Hey")
    });
    // --- heap scanning using class descriptors ---


    // +++ heap scanning using a memory snapshot +++
    const snapshot = Il2Cpp.MemorySnapshot.capture();
    snapshot.objects.filter(Il2Cpp.Filtering.IsExactly(SystemType)).forEach((instance: Il2Cpp.Object) => {
        // instance.class.type.name == "System.Type"
    });
    snapshot.free();
    // --- heap scanning using a memory snapshot ---

	

	const addr=ptr(CSharp.class("EVP.Wheel").fields[4])
	
	
	
    
});`


It says syntax
I can't run the typescript file it gives me error 
Failed to load script: script(line 1): SyntaxError: expecting '('

I have the prequesties downloaded i don't know what the problem is but i think i can't run the snippet you provided in Javascript file . I will try with the typescript again and maybe i will be lucky

But is there anyone to convert those code snippets to Javacript code to write in the _.js file instead of index.ts ? To save time

**Comment by christiancoleman** [comment]
`SyntaxError: expecting '('` specifically on Line 1 or Line 2 (depending on if you're using `use strict` I just learned is due - in my case - to not including the `--bundle` option on esbuild. That was a pain in the ass to find. I kept tweaking the package.json and tsconfig.json only to realize I accidentally stripped that argument out thinking it didn't really matter.
