### ISSUE TITLE
How to select a overloaded method?

### ISSUE THREAD

**Issue by EtherealAO** [vfsfitvnm/frida-il2cpp-bridge#2]
like frida `dexclassLoader.loadClass.overload('java.lang.String').implementation = function(args){}`

**Comment by vfsfitvnm** [comment]
Hi, upon method name clashes, a suffix _${number} is appended to the latest method name.
For instance. we'll have:
`cctor`
`cctor_2`
`cctor_3` and so on.

There's no way to select a specific overloaded method based on its signature - sorry!
