### ISSUE TITLE
Cannot read property 'isEqualOrAbove' of undefined 

### ISSUE THREAD

**Issue by Luckrat** [vfsfitvnm/frida-il2cpp-bridge#20]
i found this bug look like its cant find unity version i attack screenshot also 
_< senitive information >_
thank you

**Comment by vfsfitvnm** [comment]
You didn't call `Il2Cpp.initialize()`

**Comment by Luckrat** [comment]
Ty but I already used that command in this ss I just show the error still have that error
After trying Il2Cpp.initialize() and il2cpp.Dumper.classicDump()
@vfsfitvnm

**Comment by vfsfitvnm** [comment]
@Luckrat 
I downloaded that game.
This is a bit tricky: the `Il2CppDomain` always shows 0 assemblies. This is where I check if the main domain has been loaded:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/initialize.ts#L49

As you can see, `Il2Cpp.initialize()` will never finish; however the unity version is set before that line:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/initialize.ts#L46

Your error means the unity version has not been set yet, so you are probably missing something. However, you can't dump the game anyway because the domain has 0 assemblies (don't know why?, can this be solved?).

**Comment by Luckrat** [comment]
@vfsfitvnm  if u see metadata in bin folder of apk it's not the real metadata il2cpp highly encrypted it's does not make sense if the module dump it without metadata there no solution for it damn I think I thot it's will work but na I tried different games also like °°°°° but I found same error!
Maybe I can attach _'js file if u wants !

**Comment by vfsfitvnm** [comment]
@Luckrat 
I performed few minor changes that will help you.
I now check the domain load status via `il2cpp_get_corlib`: if it returns `NULL`, wait.
So, `Il2Cpp.initialize()` will now correctly get its job done.

You can dump the game in two ways:
- `Il2Cpp.Dumper.snapshotDump("dump.cs", "/storage/emulated/0")`, it's very straightforward ([more info](https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/DOC.md#dump)).
- Using `System.Reflection` classes:
    ```ts
    import "frida-il2cpp-bridge";
    
    async function main() {
        await Il2Cpp.initialize();

        const AppDomain = Il2Cpp.Image.corlib.classes["System.AppDomain"].methods.get_CurrentDomain.invoke<Il2Cpp.Object>();
    
        for (let assembly of AppDomain.methods.GetAssemblies_.invoke<Il2Cpp.Array<Il2Cpp.Object>>()) {
            // assembly is a System.Reflection.MonoAssembly, but we need a System.Reflection.Assembly:
            assembly = assembly.base.base;
            console.log(assembly.methods.GetSimpleName.invoke<Il2Cpp.String>());
        
            // it's your turn now
        }
    }
    
    main().catch(error => console.log(error.stack));
    ```

**Comment by Luckrat** [comment]
Really quick response thank you so much after class I will try and let you know thank you again 🥰

**Comment by Luckrat** [comment]
there still same error @vfsfitvnm as u can see in ss i did something wrong? i got 0byte dump.cs in storage
_seen_

**Comment by vfsfitvnm** [comment]
@Luckrat 
If you already upgraded the package to `0.4.5`, then I don't know what to say. I tried this myself and works.

**Comment by Luckrat** [comment]
i upgraded to 0.4.5 look at ss you see my command stuff in previous ss is there anything i am doing wrong @vfsfitvnm if i get any contact i mean discord anything i can explain more properly
![Screenshot 2021-08-03 222958](https://user-images.githubusercontent.com/88358818/128059973-e48844a8-d1a4-41a2-ad17-02448255247c.png)

**Comment by vfsfitvnm** [comment]
![Screenshot_20210803_193038](https://user-images.githubusercontent.com/46219656/128060422-ccd12c94-e8e4-4b71-8331-eebc2b550673.png)
@Luckrat Ok but, did you remove the old package? Did you `Il2Cpp.initialize()`?

**Comment by Luckrat** [comment]
yes i removed package generated new module with latest frida-bridge zip also _.js then compile again added command Il2Cpp.initialize() but still same please can get a contact so i can explain @vfsfitvnm

**Comment by vfsfitvnm** [comment]
I'm sorry I don't provide private support. Probably you are not recompiling with `frida-compile`.

**Comment by Luckrat** [comment]
@vfsfitvnm i can understand asf i did everything again still same and yes i compile with frida see screen shot bellow on my commands and also index.ts 
_seen_

ss1 with comands i applied 
_seen_

**Comment by vfsfitvnm** [comment]
You are not recompiling with `frida-compile` (the `build` script...)

**Comment by hamilol6449** [comment]
I GOT SAME ERRORS SO I CANT FIND HOW TO FIX SO I GIVE UP XD

**Comment by Luckrat** [comment]
@vfsfitvnm as u can see compiled script using frida-compile still get error 
![Screenshot 2021-08-04 011702_LI](https://user-images.githubusercontent.com/88358818/128081678-79bb8c21-e9ab-47f8-bbc9-a73b8f83163c.jpg)
