### ISSUE TITLE
Dump DummyDLL

### ISSUE THREAD

**Issue by heqyoufree** [vfsfitvnm/frida-il2cpp-bridge#201]
Reference: [Perfare/Il2CppDumper](https://github.com/Perfare/Il2CppDumper/blob/master/Il2CppDumper/Outputs/DummyAssemblyExporter.cs)

**Comment by vfsfitvnm** [comment]
Csn you elaborate?

**Comment by heqyoufree** [comment]
Perfare's Il2CppDumper can dump from libil2cpp.so and recover the code. Then the code is write into one dll. Using dnSpy or something else can inspect more infomation.

**Comment by vfsfitvnm** [comment]
Thanks for clarifying. Unfortunately it's still unclear to me how it is done; however, what's the information `frida-il2cpp-bridge` is lacking of?

**Comment by heqyoufree** [comment]
Il2CppDumper can convert Cpp back to IL and generate a dll (DummyDLL). However, Il2CppDumper usually failed because of  encrypted global-metadata.dat and libil2cpp.so and I believe it can be easier to be done using ```frida-il2cpp-bridge```

**Comment by vfsfitvnm** [comment]
I don't think in-memory binary code can be converted to IL. I believe Il2CppDumper just crafts a `.dll` starting from the information it already has. That is, is creates a different dump format, so you can inspect it using a third party program. That's all - there is no extra information this step adds.

This feature is interesting, but I don't know how to do so - I'd have to learn how to write binary `.dll` code (and I don't want to).
I think outputting valid C# code is way more doable, but I doubt I will personally implement it.

**Comment by heqyoufree** [comment]
Yes, the ```.dll``` it created has no method body but it makes the relation between classes more clearer.

**Comment by vfsfitvnm** [comment]
Yeah. I agree the dump inspection experience should be improved. I personally use(d) `klogg`, a fast read-only text viewer - but a proper C# viewer (with goto, find references etc) is probably better. However I couldn't find any that could handle several MBs of source code.
I expect `dll` viewer tools do an excellent job at this, but as I stated before, I personally won't support such dump format - contributions are welcomed, of course.
