### ISSUE TITLE
Cannot read property 'isEqualOrAbove' of undefined 

### ISSUE THREAD

**Issue by ImSevol** [vfsfitvnm/frida-il2cpp-bridge#21]
При использовании столкнулся с ошибкой "Cannot read property 'isEqualOrAbove' of undefined"
Где я мог её допустить
_seen_

**Comment by vfsfitvnm** [comment]
This is not a bug.
See #20

**Comment by ImSevol** [comment]
@vfsfitvnm я следовал этому туториалу: https://hackcatml.tistory.com/m/94 . С моей стороны всё верно. 
не могли бы вы дать скомпилированный _.js для теста. Я могу дать свой файл для теста.
