### ISSUE TITLE
How I can can hook functions?

### ISSUE THREAD

**Issue by Abdelrahmanamhawy** [vfsfitvnm/frida-il2cpp-bridge#216]
Hello , 

Here 's my code 👍 
```ts
const Modulebase = Module.load("libil2cpp.so").base
const CSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;
const targetClass = CSharp.class("gameManager")
const story = "Hello"
//console.log(ptr(story))
var targetMethod = targetClass.method("addMoney")
var diff1 = (ptr(CSharp)-Modulebase)
var diff2 = (ptr(targetClass)-ptr(CSharp))
```

I am trying to hook the targetmetod variable ,but i can't . In the dump.cs file dumped by the ill2cppdumper ,this method has an offset of ( 0x6DD060) . 
My debugging output is as follows : 

Difference between libil2cpp and Assembly-CSharp  : 22624712
Difference between Assembly-CSharp and TargetClass:  466822088

libil2cpp Base: 0x7c57990000
ptr(Assembly-Csharp) : 0x7c563fc638
targetMethod : System.Void addMoney(System.Int32 amount, System.Boolean counting); // 0x00ae7358
ptr(targetMethod):  0x7c6c31fe00
Instuction of the targetclass : ldr x24, #0x7c6c3aec68

I can't use the intercept function,it tells me access violation and file bug ,or can't intercept the function .
Tried heap scanning using the code in the snippets but i get a syntax error saying "SyntaxError: expecting ',' "

**Comment by vfsfitvnm** [comment]
Uhm, I see a lot of confusion here. All you need to do is:
```ts
Il2Cpp.perform(() => {
    const AssemblyCSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;
    const gameManager = AssemblyCSharp.class("gameManager");

   gameManager.method("addMoney").implementation = function (amount: number, counting: boolean) {
       // do whatever you want
       this.method("addMoney").invoke<void>(amount + 1000, counting);
   }
});
```

**Comment by Abdelrahmanamhawy** [comment]
Failed to load script: script(line 5): SyntaxError: expecting ','

I am running the _.js file ,not the typescript file . I am guessing the code you wrote has typescript syntax in it and not Javascript . This is why it's not working

**Comment by Abdelrahmanamhawy** [comment]
> Uhm, I see a lot of confusion here. All you need to do is:
> 
> ```ts
> Il2Cpp.perform(() => {
>     const AssemblyCSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;
>     const gameManager = AssemblyCSharp.class("gameManager");
> 
>    gameManager.method("addMoney").implementation = function (amount: number, counting: boolean) {
>        // do whatever you want
>        this.method("addMoney").invoke<void>(amount + 1000, counting);
>    }
> });
> ```
