### ISSUE TITLE
Question about enumerate classes

### ISSUE THREAD

**Issue by chensem** [vfsfitvnm/frida-il2cpp-bridge#219]
Snippets in dump.cs like below
![image](https://user-images.githubusercontent.com/27469499/188603244-920fa0bf-1b90-485d-9e60-ba38dc773b37.png)
try to find this class return null
![image](https://user-images.githubusercontent.com/27469499/188603546-3594585b-9376-4c7a-99dc-72e28a5bbbb6.png)
use classes to filter can find this class
![image](https://user-images.githubusercontent.com/27469499/188603835-a27ad39a-affc-4c86-bee4-03073e6d50f6.png)
as the above show , the class's name is <>c  , so try to use the snippet as below 
![image](https://user-images.githubusercontent.com/27469499/188604195-8c088a8d-8e83-4022-a294-0a524005fca8.png)

so how to correct this snippet ?

**Comment by vfsfitvnm** [comment]
That class is a nested class, that's why it doesn't come up with `class` or `tryClass`. The `classes` property, instead, shows every class, no matter if it's nested or not. This is not a decision of my own, but this is how the il2cpp internals work!

So, you want to do this instead:
```ts
AssembleCSharp.class("LitJson.JsonMapper").nested("<>c");
```
