### ISSUE TITLE
il2cpp: cannot resolve export 

### ISSUE THREAD

**Issue by caodocument** [vfsfitvnm/frida-il2cpp-bridge#222]
A version based on 2019
[Unable to resolve](il2cpp: cannot resolve export)
dump
![image](https://user-images.githubusercontent.com/56826415/189942785-1e084568-fe65-499a-a9b7-e232e1c29502.png)

**Comment by vfsfitvnm** [comment]
I believe the il2cpp source code has been modified. Unfortunately there isn't much I can do; however what's the applicazion id? Maybe I can find a workaround
