### ISSUE TITLE
Handle for "il2cppType" cannot be null

### ISSUE THREAD

**Issue by ImSevol** [vfsfitvnm/frida-il2cpp-bridge#23]
![image](https://user-images.githubusercontent.com/62372284/129333175-d976d19b-74ec-48b7-9e29-5cbac37bf02e.png)

**Comment by vfsfitvnm** [comment]
@ImSevol 
I need to know which application your are trying to dump and the `frida-il2cpp-bridge` version.
However, it is strange that a `Il2CppType` is `NULL`.

**Comment by ImSevol** [comment]
sorry already fixed

**Comment by vfsfitvnm** [comment]
@ImSevol could you tell me what's happened? This is the same of #13.

**Comment by ImSevol** [comment]
At first I generated an incomplete dump due to an error. then I realized that I forgot Il2Cpp.initialize () and with it I also got an error, but the dump was with all the classes I needed

**Comment by vfsfitvnm** [comment]
@ImSevol 
That's fair.
However, I suggest you to update the package to v0.5.0.
