### ISSUE TITLE
Trace missing calls

### ISSUE THREAD

**Issue by sanktanglia** [vfsfitvnm/frida-il2cpp-bridge#232]
Trace appears to be missing some calls and i cant figure out why, my code is

        Il2Cpp.trace()
        .assemblies(Il2Cpp.Domain.assembly('UnityEngine.UnityWebRequestModule'))
        .and()
        .attach("detailed");

I can see some properties being called on UnityWebRequest but it cant see the constructor or other method/property for some reason

**Comment by vfsfitvnm** [comment]
How can you say some calls are being missed?

**Comment by sanktanglia** [comment]
Because I see some calls being made to properties on unity web request like
get_is_done and get_result but that's it, doesn't see it getting
constructed though nor does it show what's actually happening when the
request fails. I

**Comment by vfsfitvnm** [comment]
Well, this is not a bug or something, it really depends on the application you are dealing with. Maybe you are hooking the wrong module or class. I cannot help you further as the piece of information you collected is unhelpful

**Comment by TomieAi** [comment]
does this only work on real device xD on emulator like bluestack it doesnt have anything but it spawn the app tho
