### ISSUE TITLE
Timeout & Il2CppType cannot be NULL.

### ISSUE THREAD

**Issue by BryanGIG** [vfsfitvnm/frida-il2cpp-bridge#24]
having this issue when trying to dump big-size game
```
Failed to load script: timeout was reached
[il2cpp] Handle for "Il2CppType" cannot be NULL.
    at Object.raise (node_modules/frida-il2cpp-bridge/dist/utils/console.js:10:1)
    at new NonNullNativeStruct (node_modules/frida-il2cpp-bridge/dist/utils/native-struct.js:27:1)
    at new Il2CppType (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/type.js:13:1)
    at Il2CppParameter.get type (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/parameter.js:19:1)
    at Il2CppParameter.descriptor.get (node_modules/decorator-cache-getter/dist/index.js:9:1)
    at Il2CppClass.toString (node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/class.js:164:1)
    at node_modules/frida-il2cpp-bridge/dist/il2cpp/dumper.js:36:1
    at Generator.next (<anonymous>)
    at Function.dump (node_modules/frida-il2cpp-bridge/dist/il2cpp/dumper.js:44:1)
    at Function.classicDump (node_modules/frida-il2cpp-bridge/dist/il2cpp/dumper.js:32:1)
```

**Comment by vfsfitvnm** [comment]
@BryanGIG 
This is the same of #23 and #13.
The caller thread must be attached to the domain:
```ts
Il2Cpp.perform(() => Il2Cpp.Dumper.classicDump());
```
Can you confirm this solves the issue?

**Comment by BryanGIG** [comment]
im using, and get result as an issue
```
Il2Cpp.perform(() => {
    // it will use default directory path and file name: /<default_path>/<default_name>.cs
    Il2Cpp.Dumper.classicDump("dump.txt","/data/local/tmp")
});
```

**Comment by vfsfitvnm** [comment]
@BryanGIG 
What's the application you are trying to dump? I'll check it out

**Comment by BryanGIG** [comment]
[playstore link](https://play.google.com/store/apps/details?id=com.activision.callofduty.shooter)

**Comment by vfsfitvnm** [comment]
@BryanGIG 
I cannot play that game because it requires google play services, which I don't have. May you provide more info?

**Comment by BryanGIG** [comment]
What kind of info that i can provide?

**Comment by vfsfitvnm** [comment]
@BryanGIG 
Info such as the script you are using (both typescript and JS compiled versions)

**Comment by BryanGIG** [comment]
im using node.js v16.7.0

**Comment by vfsfitvnm** [comment]
@BryanGIG 
The node version is irrelevant, I need the source code (`index.ts` and the "compiled" `.js` files).

**Comment by BryanGIG** [comment]
sure, here's the file
[Il2cpp-bridge.zip](https://github.com/vfsfitvnm/frida-il2cpp-bridge/files/7026945/Il2cpp-bridge.zip)

**Comment by vfsfitvnm** [comment]
@BryanGIG 
The code look good to me.
However I managed to download that game and I didn't had that error. I have successfully dumped the game. So you are definitely missing something in your project setup.

**Comment by BryanGIG** [comment]
Glad to hear that, im waiting for the update😃

**Comment by vfsfitvnm** [comment]
There are no issues, so there won't be any update.

> PS: The game has a untypical unity version - some structs seems to be off, but I still managed to dump the game.
This is still true tho, `Il2Cpp.Dumper` doesn't always succeed and I don't know why.
