### ISSUE TITLE
How to free Il2Cpp.String

### ISSUE THREAD

**Issue by chensem** [vfsfitvnm/frida-il2cpp-bridge#245]
My codes like below 
![image](https://user-images.githubusercontent.com/27469499/211485172-cb24de31-a2fa-4675-973c-4a3f4e6e15cb.png)

i wonder how to free the memory

**Comment by vfsfitvnm** [comment]
As far as I know, you can't free the memory of an object (I couldn't find a way to do that).
When a thread gets detached from IL2CPP, its allocated memory is marked as eligible to be collected by the garbage collector.
