### ISSUE TITLE
Implementation returning question

### ISSUE THREAD

**Issue by HalfHydra** [vfsfitvnm/frida-il2cpp-bridge#25]
In the older days of frida-il2cpp-bridge, something like this was possible before you stopped using Interceptor.attach

```
method.intercept({
    onLeave(returnValue){
         returnValue.value += 5
    }
})
```

Is it still possible to return a value based on the "onLeave" return value now that method intercepting has been merged into method.implementation? The method is not static, so invoking it will not work.

**Comment by vfsfitvnm** [comment]
@HalfHydra 
> The method is not static, so invoking it will not work.

It should because `this` is a `Il2Cpp.Object` if the method is not static.
Consider this example:
```cs
System.Globalization.SortKey GetSortKey(System.String s, System.Globalization.CompareOptions options);
```
```ts
GetSortKey.implementation = function(s: Il2Cpp.String, options: Il2Cpp.ValueType): Il2Cpp.Object {
    const returnValue = this.methods.GetSortKey.invoke<Il2Cpp.Object>(s, options);
    // `returnValue` is the original return value

    const replacement = Il2Cpp.Object.from(returnValue.class);
    // System.Void .ctor(System.Int32 lcid, System.String source, System.Globalization.CompareOptions opt);
    replacement.methods[".ctor"].invoke(23, Il2Cpp.String.from(":)"), options);
    
    return replacement; // <-- the value you return is what will replace the original one
};
```

I had to drop `Interceptor.attach` because floating point registers are not exposed yet; so interception of methods with `System.Single` and `System.Double` as parameters wouldn't have worked correctly. However, you can still do it on your own:
```ts
Interceptor.attach(method.virtualAddress, {
    onLeave(returnValue: NativeReturnValue) {
        // ...
    }
});
```

**Comment by HalfHydra** [comment]
Ah, thanks for the swift reply, I found my issue with the example. I was using `this` incorrectly. Looking back at the readme I totally could've seen that myself with the example there too, whoops. It makes sense why the values for System.Single and System.Double would give very extreme values knowing that. Thanks again for the help!
