### ISSUE TITLE
Android Emulator

### ISSUE THREAD

**Issue by qiaozhi-4** [vfsfitvnm/frida-il2cpp-bridge#267]
Hello, there is no way to get libil2cpp.so in Android emulator

**Comment by chensem** [comment]
add option --realm=emulated , example : `frida -U com.xxx -F -l test.js --realm=emulated`

**Comment by qiaozhi-4** [comment]
> 添加选项 --realm=emulated ，例如：`frida -U com.xxx -F -l test.js --realm=emulated`

thank you
