### ISSUE TITLE
Get an object instance

### ISSUE THREAD

**Issue by qiaozhi-4** [vfsfitvnm/frida-il2cpp-bridge#268]
![image](https://user-images.githubusercontent.com/82357518/227724328-9964a7fe-e78f-4a6c-9720-53ba53d4e1fd.png)
I want to get an instance of this object, but I don't know how to create it. Here is the constructor for this class
![image](https://user-images.githubusercontent.com/82357518/227724440-9a5644be-5498-43a3-87b6-d2a442a69cea.png)
![image](https://user-images.githubusercontent.com/82357518/227724562-0de87c95-6ef5-4dba-963d-9f2c7de5d6d0.png)
I do this step and I don't know how to go down, okay

**Comment by ExternalAddress4401** [comment]
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/class.ts#L211


Try

```
let v3clazz = Il2Cpp.Domain.assembly('UnityEngine.CoreModule').image.class('UnityEngine.Vector3');
let v3obj = v3class.alloc();
v3obj.method('.ctor').invoke(x, y, z);
```

To create a new one.

To change existing objects you access the property with `.field`

```
let v3obj = v3clazz.method('get_one').invoke();
v3obj.field('x').value = 2.0;
```

**Comment by qiaozhi-4** [comment]
> https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/class.ts#L211
> 
> 尝试
> 
> ```
> let v3clazz = Il2Cpp.Domain.assembly('UnityEngine.CoreModule').image.class('UnityEngine.Vector3');
> let v3obj = v3class.alloc();
> v3obj.method('.ctor').invoke(x, y, z);
> ```
> 
> 创造一个新的。
> 
> 要更改现有对象，您可以使用`.field`
> 
> ```
> let v3obj = v3clazz.method('get_one').invoke();
> v3obj.field('x').value = 2.0;
> ```

Thank you. Try it right away.

**Comment by qiaozhi-4** [comment]
> https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/master/src/il2cpp/structs/class.ts#L211
> 
> 试一试
> 
> ```
> let v3clazz = Il2Cpp.Domain.assembly('UnityEngine.CoreModule').image.class('UnityEngine.Vector3');
> let v3obj = v3class.alloc();
> v3obj.method('.ctor').invoke(x, y, z);
> ```
> 
> 创造一个新的。
> 
> 要更改现有对象，您可以使用`.field`
> 
> ```
> let v3obj = v3clazz.method('get_one').invoke();
> v3obj.field('x').value = 2.0;
> ```
Thank you. It's done
