### ISSUE TITLE
Missing ESM imports

### ISSUE THREAD

**Issue by c01ns** [vfsfitvnm/frida-il2cpp-bridge#269]
node verison
![image](https://user-images.githubusercontent.com/44087084/227754313-a55f17cf-e00f-4a8b-9fa2-df0f5d25bd03.png)
![image](https://user-images.githubusercontent.com/44087084/227754314-fb2b59b4-7c45-45e5-8d72-6f6249d04035.png)

npm run build
![image](https://user-images.githubusercontent.com/44087084/227754300-efc76f91-dfee-4cf7-8a04-8df7dd02c82e.png)

**Comment by vfsfitvnm** [comment]
Don't use `tsc` - I've adopted https://github.com/cevek/ttypescript so I could move CModules to their own files (for syntax highlighting, code completion, code formatting...).

You need to call `npm run prepare` instead (which is equivalent to `npm exec ttsc`).

However yes, I forgot to append the `.js` extension  when importing those two files (I recently moved to ESM modules).
