### ISSUE TITLE
Tracing question

### ISSUE THREAD

**Issue by qiaozhi-4** [vfsfitvnm/frida-il2cpp-bridge#270]
I hope that when filtering, the filtering condition is dynamic, that is, the method after printing once is not printed, but I found that this method he does not judge every time
![image](https://user-images.githubusercontent.com/82357518/227900795-9706768b-e4c8-4d8f-9ae3-92d89db70eeb.png)

**Comment by vfsfitvnm** [comment]
I do not understand I'm afraid. Is #27 what you are looking for?

**Comment by qiaozhi-4** [comment]
> 我不明白我害怕。#27是你要找的吗？

Yes, thank you very much.

**Comment by qiaozhi-4** [comment]
> 我不明白我害怕。#27是你要找的吗？

Hello, that code doesn't do what I want, what I want is for all the methods to be called once and then I put it in set, and then the method won't be printed again, so that I can eliminate the method that keeps being called in the game until I click, so that I can easily find the method that I want

**Comment by vfsfitvnm** [comment]
That's not implemented yet, but I will do that soon-ish!

**Comment by qiaozhi-4** [comment]
> 这还没有实施，但我会尽快做到这一点！

非常期待!!

**Comment by qiaozhi-4** [comment]
> 这还没有实施，但我会尽快做到这一点！
I also have the idea that when I know what a method does, I want to know who called it,
