### ISSUE TITLE
send() instead of console.log?

### ISSUE THREAD

**Issue by 0xzer** [vfsfitvnm/frida-il2cpp-bridge#272]
is there an option for this? Because I would like to save everything it debugs instead of sitting in terminal looking like console.log redirects to send() or do i edit the src for that?

**Comment by vfsfitvnm** [comment]
You can always override `console.log`:
```ts
console.log = (...args: any[]) => send(args);
```

Or redirect stdout/stderr to a file:
```sh
frida ... 2>&1 | tee outfile
```

**Comment by vfsfitvnm** [comment]
(The discussion is still open if you want to elaborate)
