### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by 350030173** [vfsfitvnm/frida-il2cpp-bridge#301]
version 0.8.1
after compile have some error
![image](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/20263746/b7110e58-5750-4a70-ac13-b2819bdcf1c6)

and before ,i use frida-compile.cmd(the version is 10.2.4),dont have the error info

**Comment by vfsfitvnm** [comment]
Upgrade your `frida-compile` version!

**Comment by commonuserlol** [comment]
> Upgrade your `frida-compile` version!

as i understand it, this is the new version of the frida-compile that does this too.

```
[user@user-80xr test]$ frida-compile index.ts -o _.js
[user@user-80xr test]$ frida-compile --version
16.0.19
```
i also have this as result
![asd](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/111648021/d1162e6b-4fa6-4382-8bae-0f70409c325d)

it is worth noting that frida normally uses such a script, but if you want to obfuscate it, use esbuild

**Comment by 350030173** [comment]
i ask chatgpt,it say :nodejs version too low,my windows is 7 o(╥﹏╥)o

**Comment by commonuserlol** [comment]
to be honest, chatgpt sometimes dumbo, ignore these if you need just run script, it will work; if you need obfuscate it - use esbuild

**Comment by 350030173** [comment]
> Upgrade your `frida-compile` version!

i Upgrade `frida-compile` version,but still have this problem

**Comment by vfsfitvnm** [comment]
Would you share your whole workflow? I.e. the commands you are launching, the error message...

**Comment by commonuserlol** [comment]
this can hardly be called a error... this is an innovation by frida-compile (which still works fine with frida)

**Comment by 350030173** [comment]
> Would you share your whole workflow? I.e. the commands you are launching, the error message...


package.json and tsconfig.json copy from [here ](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Installation)

**frida-compile -o test.js -w test.ts**
![compile](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/20263746/a6739168-cb42-4610-8caa-cb86a793226c)

**out:**
**a display error when I open the js file**
![out](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/20263746/e11fa082-85dd-4087-bfaa-e72e3847e404)

**frida spawn:**
![frida](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/20263746/02441f3c-8a4a-43b3-9bbe-348133a55746)
**There is no error message output**
