### ISSUE TITLE
Game can't be dump

### ISSUE THREAD

**Issue by thienha1** [vfsfitvnm/frida-il2cpp-bridge#308]
![Capture](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/18132856/ec306978-b710-4480-b27c-a8dd9f3cca64)
I dont know this happen for now, old version of this game work normal! Maybe they obfuscated all name?

Source code:
```
Il2Cpp.perform(() => {
  // console.log(Il2Cpp.unityVersion);
    Il2Cpp.dump("hsrsea.cs");
});
```

**Comment by commonuserlol** [comment]
mihoyo games have modified il2cpp binaries and hidden exports. thats why it don't work with common il2cpp tools

**Comment by vfsfitvnm** [comment]
"No such file or directory" means it couldn't create the file where to write the dump, pass the directory as the second parameter:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/ae7ef9ea2ca0e33fe50994179b2a4751541549e4/src/il2cpp/dump.ts#L3

(and make sure it exists!)

**Comment by commonuserlol** [comment]
hmm ik that genshin (mobile version, idk about pc) have protections like hidden exports, encrypted metadata, etc... maybe hsr **still** not

**Comment by thienha1** [comment]
> "No such file or directory" means it couldn't create the file where to write the dump, pass the directory as the second parameter:
> 
> https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/ae7ef9ea2ca0e33fe50994179b2a4751541549e4/src/il2cpp/dump.ts#L3
> 
> (and make sure it exists!)

I created this file
![Capture](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/18132856/322abed8-29be-4b1d-9fbc-9b3c4fa12f6f)

And still got this error
![Capture](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/18132856/03d397f7-5cac-42be-8a1d-99729fa24b4f)
Code:
```
Il2Cpp.perform(() => {
  // console.log(Il2Cpp.unityVersion);
    Il2Cpp.dump("hsrsea.cs", "D:\APKLabs\Dumped Honkai Star Rail SEA");
}, "free");
```

**Comment by thienha1** [comment]
> hmm ik that genshin (mobile version, idk about pc) have protections like hidden exports, encrypted metadata, etc... maybe hsr **still** not

yeah mihoyo did that but still i dunno how modder could dump those encrypted file in PC... What tools they use?

**Comment by commonuserlol** [comment]
idk sorry, you can try explore cheats for these games (akebi source available only for 3.2, i seen some hsr cheat). maybe it will help u

**Comment by vfsfitvnm** [comment]
@thienha1
Oh yeah I think I know what's wrong (I don't have Windows so I can't really test...).

Here's how I generate the full path:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/ae7ef9ea2ca0e33fe50994179b2a4751541549e4/src/il2cpp/dump.ts#L6

But as you can see, I use the Unix file separator char (`/`) - illegal on Windows - instead of the correct one (`\`).

Would you patch either your local copy (`node_modules/frida-il2cpp-bridge/dist/index.js`) or the bundled script (`_agent.js`) and see if it works?

**Comment by thienha1** [comment]
> @thienha1 Oh yeah I think I know what's wrong (I don't have Windows so I can't really test...).
> 
> Here's how I generate the full path:
> 
> https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/ae7ef9ea2ca0e33fe50994179b2a4751541549e4/src/il2cpp/dump.ts#L6
> 
> But as you can see, I use the Unix file separator char (`/`) - illegal on Windows - instead of the correct one (`\`).
> 
> Would you patch either your local copy (`node_modules/frida-il2cpp-bridge/dist/index.js`) or the bundled script (`_agent.js`) and see if it works?

I updated your script to latest version
![Capture](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/18132856/9bc1d5e6-c06a-4eee-aace-240427db742c)
But I tried this function dump without parameter 2 before of this game in old version, it work smoothly! Now I tried all of this with latest version for now, not work at all!

**Comment by vfsfitvnm** [comment]
@thienha1 
Hmm, this is weird to be honest.
However, just to make sure, would you replace the `/` with `\` at line 648?
And then:
```ts
Il2Cpp.perform(() => {
    Il2Cpp.dump("hsrsea.cs", "D:\APKLabs\Dumped Honkai Star Rail SEA");
}, "free");
```

Another possibility is the app cannot write to that path, but again, I have no idea how it works on Windows; does the following Frida script works?
```ts
const file = new File("D:\APKLabs\Dumped Honkai Star Rail SEA\hello.cs", "w");
file.write("hello!");
file.flush();
file.close();
```

**Comment by vfsfitvnm** [comment]
And, shouldn't it be: `D:\\<and so on>`? Notice the double backslash

**Comment by thienha1** [comment]
> And, shouldn't it be: `D:\\<and so on>`? Notice the double backslash

Yeah, it temp working and get other issue...
![Capture](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/18132856/930f0b27-2618-48ac-822c-428fd936962a)

**Comment by vfsfitvnm** [comment]
You need to determine the Unity version by yourself (it doesn't have to be precise, though), then. Unfortunately I don't have Windows so I cannot find a workaround by myself.

Then, see https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/96#issuecomment-1042788077

**Comment by UncleNiceCock** [comment]
> > hmm ik that genshin (mobile version, idk about pc) have protections like hidden exports, encrypted metadata, etc... maybe hsr **still** not
> 
> yeah mihoyo did that but still i dunno how modder could dump those encrypted file in PC... What tools they use?

private custom made tools
