### ISSUE TITLE
Il2Cpp.application is null

### ISSUE THREAD

**Issue by commonuserlol** [vfsfitvnm/frida-il2cpp-bridge#310]
hey, im just tried dump app but as title says `Il2Cpp.application` is null
```
-> Il2Cpp.application
{
    "dataPath": null,
    "identifier": null,
    "version": null
}
```
unity is `2020.3.26f1` and app name is `com.ekindiegames.ElectricTrains` (you can find in google play or https://electric-trains.en.uptodown.com/android/download), android is 12.1 (but i think it not matter)

**Comment by vfsfitvnm** [comment]
Yeah, it can totally happen: it depends on whether the compiler stripped out those methods (it does if they are unused). , I'll take a look anyway as soon as I can (just in case)

**Comment by vfsfitvnm** [comment]
Yup, I confirm what I said. Unfortunately, you have to either monkey-patch that object or provide the required parameters where needed!
