### ISSUE TITLE
How to create object[] instance?

### ISSUE THREAD

**Issue by broqdev** [vfsfitvnm/frida-il2cpp-bridge#317]
Hey, first great tool. Thank you for the work!

I'm trying to invoke https://docs.unity3d.com/ScriptReference/AndroidJavaObject.CallStatic.html , which is
```java
public void CallStatic(string methodName, params object[] args);
```
I have successfully done that by using a empty System.Object[] object. But when I try to do something like
```java
CallStatic("MyMethod", [0, 1, "test"])
```
I cannot find a proper way to do that. I have tried Il2Cpp.Array.array, or System.Object[].ctor. But all got errors. Could you please help to show some way for doing that?

**Comment by vfsfitvnm** [comment]
Hi, here you are:
```ts
Il2Cpp.array(Il2Cpp.corlib.class("System.Object"), [ ... ]);
```
Beware of you can only pass `Il2Cpp.Object`s.

Full example:
```ts
const SystemInt32 = Il2Cpp.corlib.class("System.Int32");
const SystemObject = Il2Cpp.corlib.class("System.Object");

const zeroBoxed = SystemInt32.new();
zeroBoxed.m_value.value = 0;

const oneBoxed = SystemInt32.new();
oneBoxed.m_value.value = 1;

const test = Il2Cpp.string("test");

CallStatic.invoke(Il2Cpp.string("MyMethod"), Il2Cpp.array(SystemObject, [zeroBoxed, oneBoxed, test]));
```

**Comment by broqdev** [comment]
verified it works. Thanks!
