### ISSUE TITLE
how it's work ?

### ISSUE THREAD

**Issue by QM4RS** [vfsfitvnm/frida-il2cpp-bridge#318]
Hello. I have worked extensively with Frida, but I have never used the TypeScript modules before. Everything I have done so far has been written in JavaScript. It seems like this project could be very helpful to me, but I really don't know how to use it. Is there anything specific I need to install? What programming language can I use with it? I would appreciate it if you could guide me on this matter.

**Comment by SMEDjs** [comment]
You can read https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki

**Comment by vfsfitvnm** [comment]
Other than the [wiki](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Installation), [here](https://github.com/oleavr/frida-agent-example) you can find the general Frida setup when using TypeScript and [here](https://github.com/vfsfitvnm/frida-il2cpp-bridge/network/dependents) you can view other projects using `frida-il2cpp-bridge`.

However, nobody forces you to use TypeScript: you can still consume this module using JavaScript (but I wouldn't recommend it if you have a desktop computer).

PS: [\@fridadotre](https://t.me/fridadotre) might help you as well!

**Comment by QM4RS** [comment]
> Other than the [wiki](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Installation), [here](https://github.com/oleavr/frida-agent-example) you can find the general Frida setup when using TypeScript and [here](https://github.com/vfsfitvnm/frida-il2cpp-bridge/network/dependents) you can view other projects using `frida-il2cpp-bridge`.
> 
> However, nobody forces you to use TypeScript: you can still consume this module using JavaScript (but I wouldn't recommend it if you have a desktop computer).
> 
> PS: [@fridadotre](https://t.me/fridadotre) might help you as well!

I think because I have never worked with TypeScript before (let alone using it for Frida), I can't work on this project right now. Until then, I have to work with JavaScript and hope that you provide a sample video tutorial for learning this tool.
