### ISSUE TITLE
can make hook mono(dll)?

### ISSUE THREAD

**Issue by 350030173** [vfsfitvnm/frida-il2cpp-bridge#32]
Refer to the link ：https://github.com/axhlzy/Il2CppHookScripts/blob/master/MonoHook/Mfun.js
this script can hook mono method，but unstable
test game:https://www.taptap.com/app/212904

**Comment by vfsfitvnm** [comment]
Adding support for mono should be easy, however it's used less and less: I don't feel like the effort will be rewarded. It would be quite difficult to find mono games with different unity versions that I can test.
Also, this package should be renamed to `frida-unity-bridge` at that point (not a problem).

Meanwhile, this is probably what you are looking for: https://github.com/NorthwaveSecurity/fridax
