### ISSUE TITLE
How to get each value of GameObject[]

### ISSUE THREAD

**Issue by chichi-cc** [vfsfitvnm/frida-il2cpp-bridge#328]
When I got UnityEngine.GameObject[] and i can get the length
But when I use the for loop to get each child, I get undefined
How can I get this correctly

**Comment by vfsfitvnm** [comment]
A (reproducible) code snippet would definitely help!

**Comment by chichi-cc** [comment]
> A (reproducible) code snippet would definitely help!

static UnityEngine.GameObject[] FindGameObjectsWithTag(System.String tag);

const coreMoudule = Il2Cpp.Domain.assembly("UnityEngine.CoreModule").image;
const GameObject = coreMoudule.class("UnityEngine.GameObject");
const obj = this.method('OnLateUpdate').invoke();

**Comment by chichi-cc** [comment]
I made a simple mistake and have fixed the problem, thank you

**Comment by vfsfitvnm** [comment]
That's fine, however if you post the solution here so that everyone can benefit from it!
