### ISSUE TITLE
Error: illegal instruction on initialization step.

### ISSUE THREAD

**Issue by truelecter** [vfsfitvnm/frida-il2cpp-bridge#33]
Currently for third.party.app you'll receive `Error: illegal instruction` when calling 
```js
Il2Cpp.perform(() => {
    // ... literally anything. 
   console.log('It works');
})
```
when spawning app with `frida -U -f third.party.app -l _.js --no-pause --runtime=v8`.

After debugging this error, I found that issues is with `Il2Cpp.Api._getCorlib()` call and for Il2Cpp.perform line 83 particularly:

https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/fa32a68cb2399f82957f6f5ee9149030676bea6e/src/il2cpp/base.ts#L81-L85

Currently I fixed this with simple and ugly patch right before if statement
```js
function wa(milis) {
    return new Promise(resolve => setTimeout(resolve, milis));
}

while (true) {
    try {
        Il2Cpp.Api._getCorlib()
        break;
    } catch (e) {
        console.log(e);
        await wa(100);
    }    
} 
```

Any suggestions what am I doing wrong?

OS: Android 9
Magisk: 23 (23000), App: 23 (23000)
Frida server: 15.1.1-1 (from magisk module). Tried with static binaries from [frida/frida](https://github.com/frida/frida/releases/tag/15.1.1) ([this one](https://github.com/frida/frida/releases/download/15.1.1/frida-server-15.1.1-android-arm64.xz) exactly) as well

**Comment by vfsfitvnm** [comment]
Hi, thanks for the issue.

I installed that game and there is no issue with `frida-il2cpp-bridge`: the game actually has its `libil2cpp.so` encrypted/obfuscated.
In fact, you won't able to analyze it with a disassembler.

This is the output of `inform(hexdump(Il2Cpp.Api._getCorlib, { length: 4 }));`:
![Screenshot_20210913_154134](https://user-images.githubusercontent.com/46219656/133097738-000b5c0e-04d5-434b-ac87-a38558b9781a.png)

The first line is printed when the app is spawned: as you can see, `0x0c4341e7` is not a valid instruction, that's why the illegal istruction error occurs. After a while, the second line is printed. In that occasion,  there will be `0x3e570014`: this is a [valid](https://armconverter.com/?disasm&code=3e570014) instructon.

My guess is this app has some sort of protection against static analysis.
The fastest solution here is what you already came up with:
```ts
while (true) {
    try {
        Instruction.parse(Il2Cpp.Api._getCorlib);
        break;
    } catch (e) {
        await new Promise(resolve => setTimeout(resolve, 100));
    }    
}
```

**Comment by truelecter** [comment]
So, from code perspective, instead of patching library code in node modules I can put same while-true block before `Il2Cpp.perform`? Or in this case  `Il2Cpp.perform` will be obsolete?

And another offtopic question regarding obfuscation: is it possible that after startup, game deobfuscates il2cpp.so in memory and dump will be statically-analyzable?

**Comment by vfsfitvnm** [comment]
> So, from code perspective, instead of patching library code in node modules I can put same while-true block before `Il2Cpp.perform`? Or in this case `Il2Cpp.perform` will be obsolete?

 Yes, in this case you can't use `await`, but this one will work:
```ts
const interval = setInterval(() => {
    try {
        Instruction.parse(Il2Cpp.Api._getCorlib);

        clearInterval(interval);

        Il2Cpp.perform(main);
    } catch (e) {}
}, 100);

function main() {
    console.log("Ready!", Il2Cpp.unityVersion);
}
```

> And another offtopic question regarding obfuscation: is it possible that after startup, game deobfuscates il2cpp.so in memory and dump will be statically-analyzable?

What does "dump" refer to (il2cpp dump - classes, methods- or deobfuscated/decrypted libil2cpp.so dump)?

**Comment by truelecter** [comment]
Thanks for the code snippet!



> What does "dump" refer to (il2cpp dump - classes, methods- or deobfuscated/decrypted libil2cpp.so dump)?

libil2cpp.so dump from game process memory which (as I understand) should be decrypted when game fully launches

**Comment by vfsfitvnm** [comment]
> libil2cpp.so dump from game process memory which (as I understand) should be decrypted when game fully launches

Well, technically something along these lines should work:
```ts
function main() {
    console.log("Ready!", Il2Cpp.unityVersion);

    const path = `${Il2Cpp.Dumper.defaultDirectoryPath}/libil2cpp.so`;
    const file = new File(path, "w");
    
    for (const range of Il2Cpp.module.enumerateRanges("---")) {
        file.write(range.base.readByteArray(range.size)!);
    }
    
    file.flush();
    file.close(); 

    console.log(`File saved to ${path}`);
}
```

Just tested and (kind of?) works on ghidra. I said kind of because I didn't perform a full-analysis and so there could be problems.

**Comment by truelecter** [comment]
Thanks a lot!
