### ISSUE TITLE
How to hook operators?

### ISSUE THREAD

**Issue by afk-Legacy** [vfsfitvnm/frida-il2cpp-bridge#35]
Hey! I wanted to ask regarding how can operators be hooked on, an example:

![image](https://user-images.githubusercontent.com/83068093/133547461-a3224986-7dba-427c-8227-8859c379e8bd.png)

**Comment by afk-Legacy** [comment]
This worked.

`const EgoPoint = AssemblyCSharp.classes.EgoPoint;
    const SetFloat = EgoPoint.methods.SetFloat;
    const pointInString = EgoPoint.methods["ToString_"];

    
    EgoPoint.methods["op_Subtraction"].implementation = function(org : Il2Cpp.Object, value: Il2Cpp.Object) : Il2Cpp.Object
    {

        return this.methods["op_Addition"].invoke<Il2Cpp.Object>(org, value);
    }`

**Comment by vfsfitvnm** [comment]
You have to follow [this](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/operator-overloads) table so you will know how these methods are named.

By the way, I recommend inspecting the dump produced by this package!

**Comment by afk-Legacy** [comment]
@vfsfitvnm Thanks, will definitely check it out. Btw, do you happen to have any snippets regarding Lists? I am trying to log a List here but facing errors.

```
pointInString.implementation = function (format : Il2Cpp.String) : Il2Cpp.String
    {
        
        const List = this.handle.add(EgoPoint.fields.Point.offset).readPointer();
        const state = new Il2Cpp.Array<number>(List);

        log( JSON.stringify(state.get(0)) );
        //log(JSON.stringify(state));
        return this.methods["ToString_"].invoke<Il2Cpp.String>(format);
    }
```

**Comment by vfsfitvnm** [comment]
Do you mean Lists or Arrays? Because are just like `Il2Cpp.Object` like anything else, arrays have their `Il2Cpp.Array` class. By the way, please open a new issue (if you think there is an issue) or a discussion at https://github.com/vfsfitvnm/frida-il2cpp-bridge/discussions/categories/q-a
