### ISSUE TITLE
How to create a http Request

### ISSUE THREAD

**Issue by TFireOps** [vfsfitvnm/frida-il2cpp-bridge#351]
When using this project, I need to retrieve some data and send it to the server. However, I haven't found a solution to send HTTP requests. I've imported axios and fetch, but neither of them is working for sending requests. Is there a way to use JavaScript to send HTTP requests in this Frida project? Since it's not an Android environment, I can't use Java from Android. The operating system is Ubuntu. I hope someone can help me with this!

**Comment by commonuserlol** [comment]
find classes which represents http and use them

**Comment by thinhbuzz** [comment]
use http frida package (available on npm)

**Comment by bluewave41** [comment]
If the dump has HTTP methods you can use those.

If not, Frida has an HTTP shim you can use with frida-compile: https://github.com/frida/gumjs-http

ESBuild also supports [aliasing](https://esbuild.github.io/api/#alias) which I think I used to load the frida shims as frida compile has become pretty barebones and has lost support for numerous features I used.
