### ISSUE TITLE
dlopen hook doesn't work on Android 8.1

### ISSUE THREAD

**Issue by vfsfitvnm** [vfsfitvnm/frida-il2cpp-bridge#360]
https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/359#issuecomment-1703745592

(I need to find a Unity app I can run on the official Android x86 emulator first)

CC: @Flechaa @thinhbuzz

**Comment by Flechaa** [comment]
What about this package: com.noodlecake.altosadventure

**Comment by vfsfitvnm** [comment]
Thanks, I can reproduce.

**Comment by Flechaa** [comment]
It seems like my device doesn't use those hooks as I get
```
Error: There are no targets to hook, please file a bug
```

**Comment by vfsfitvnm** [comment]
@Flechaa That's very unfortunate. Can you debug it?
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/ad0a65f6683e8291b7d00442f0378c200e602385/src/utils/native-wait.ts

**Comment by Flechaa** [comment]
Both of this exports return null, both dlopen and android_dlopen_ext.
https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/ad0a65f6683e8291b7d00442f0378c200e602385/src/utils/native-wait.ts#L41

How could I discover if there's an alternative export? Or is this a problem with frida?

**Comment by vfsfitvnm** [comment]
Would you try
```ts
Module.findExportByName(null, "dlopen" /*and then */ "android_dlopen_ext")
```

**Comment by Flechaa** [comment]
Yes! That works, only problem now is that the game seems to hang after that.

**Comment by vfsfitvnm** [comment]
Hmm that makes things way harder to debug, I doubt there's anything I can do without having access to the physical device :/

I think I'll just add a `setInterval`-based function instead of relying on `dlopen`

**Comment by Flechaa** [comment]
I am using Android 7 as well, not Android 8.1 as described in the issue.

**Comment by vfsfitvnm** [comment]
Thanks, I could reproduce. Frida can't hook `dlopen` :P, hence the crash, let me see what I can do
