### ISSUE TITLE
how to edit fields? if possible, without using field

### ISSUE THREAD

**Issue by EduModsS** [vfsfitvnm/frida-il2cpp-bridge#362]
i want edit field using fieldName or fieldOfsset, let's say the class name is 'testClass' and have only method called '.ctor' and have field 'testField' and only offset 0x1C, fieldType = long, how fo edit? and if fieldType is int how to correct edit? thanks

**Comment by vfsfitvnm** [comment]
If the field is static, you need the pointer to the class' static fields (`il2cpp_class_get_static_field_data`), then simply add the field offset to it, then `readInt` or whatever.
Otherwise, use the object pointer instead.

**Comment by EduModsS** [comment]
> 

if the field is not static? I learned to edit using the name, but I didn't find anything about going by his offset, how to do it by offset? using class object

**Comment by vfsfitvnm** [comment]
This is how I do it: https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/3754f1e9ee77eadede4953e11bb647cb0a2ec025/src/il2cpp/structs/field.ts#L117
