### ISSUE TITLE
Couldn't resolve export il2cpp_get_corlib

### ISSUE THREAD

**Issue by EduModsS** [vfsfitvnm/frida-il2cpp-bridge#363]
at r (/node_modules/frida-il2cpp-bridge/dist/index.js:586)
    at get getCorlib (/node_modules/frida-il2cpp-bridge/dist/index.js:417)
    at call (native)
    at <anonymous> (/node_modules/frida-il2cpp-bridge/dist/index.js:41)
    at initialize (/node_modules/frida-il2cpp-bridge/dis

**Comment by xiaozouzhiqiang** [comment]
I also encountered this problem, I don't know if it is because the il2cpp_get_corlib function does not exist in the libil2cpp.so export table

**Comment by vfsfitvnm** [comment]
It looks like game doesn't have that (kind of necessary) export, but I think there's a workaround. What are the app name and platform?

**Comment by EduModsS** [comment]
> It looks like game doesn't have that (kind of necessary) export, but I think there's a workaround. What are the app name and platform?

it was in 2 different games..., supersus and also in critical ops

**Comment by vfsfitvnm** [comment]
Both games stripped out every il2cpp export, I don't think there's much I can do to effectively detect the addresses. You have to inspect `libil2cpp.so` using a disassembler, find the addresses manually and patch the source code of `frida-il2cpp-bridge`. See https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/300

I could definitely find a replacement for `il2cpp_get_corlib`, but it wouldn't solve much, unfortunately...
