### ISSUE TITLE
Property 'fileName' does not exist on type 'void'.

### ISSUE THREAD

**Issue by xiaozouzhiqiang** [vfsfitvnm/frida-il2cpp-bridge#364]
When using the code Il2Cpp.dump().fileName("dump.cs").classes().build();, an error is prompted, Property 'fileName' does not exist on type 'void'.

**Comment by vfsfitvnm** [comment]
Please update to the latest version and read [this](https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Snippets#dumping) snippet
