### ISSUE TITLE
--realm=emulated cause Failed to attach: the connection is closed

### ISSUE THREAD

**Issue by lyf-is-coding** [vfsfitvnm/frida-il2cpp-bridge#370]
Hello,
Here is my frida command: `frida -U -f com.LiberalDust.DarkSurvival -l dist/agent.js`
When I run it, I can start the game normally but using Il2Cpp command cause an error: `frida.core.RPCException: Error: unable to find module 'libil2cpp.so'`
I looked thorugh all the Issues and found that --realm=emulated help fix the libil2cpp.so problem.
But when I run my frida command with the --realm=emulated, I got another error: `Failed to attach: the connection is closed`
Tried with another game `com.simple.game.supercat` and --realm=emulated didn't cause any problem.
How can I fix that?
Thanks.

I'm using LDPlayer 9.0.57, Android 9.0 64bit
frida-server-16.1.4-android-x86_64
[my dependencies](https://imgur.com/a/sRE0K3d)

**Comment by vfsfitvnm** [comment]
Hi, I'm not sure this is related to `frida-il2cpp-bridge` at all; it looks like a frida problem to me. What did you try so far? Are you sure is `frida-il2cpp-bridge` to cause the connection crash?

**Comment by AkaShrug** [comment]
spawning on emulated realm doesnt always work on most emulators , your best bet is attaching via pid after game loads assuming there is no protection or check
