### ISSUE TITLE
problem in pack or compile

### ISSUE THREAD

**Issue by QM4RS** [vfsfitvnm/frida-il2cpp-bridge#373]
Hi everyone 
The problem I have with Frida Compile is that it doesn't run correctly on some devices and emulators.
I use the command
`frida-compile src/index.ta -o dist/agent.js`
And
`objection patchapk -s app.apk --architecture armeabi-v7a -V 16.1.3 -c config.json -l dist/agent.js`
To compile my own file. It works very well on my phone. But it doesn't even run on the phone of many users and also the emulator.
There is definitely a problem with the compiler. Because one of my friends packed my script using Web Pack and surprisingly it is responsive on all devices. Thank you for helping me if you have any specific advice on this matter ❤️

**Comment by vfsfitvnm** [comment]
Thanks for reporting, however this can't be related to `frida-il2cpp-bridge` as you already know.
I personally use `esbuild`. Also, make sure to use the latest `frida-compile`

**Comment by QM4RS** [comment]
> Thanks for reporting, however this can't be related to `frida-il2cpp-bridge` as you already know. I personally use `esbuild`. Also, make sure to use the latest `frida-compile`

should I report it on Frida's GitHub page? 
and tnx for your suggest "esbuild"

**Comment by vfsfitvnm** [comment]
You should investigate a little further, at the very least: "it doesn't even run on the phone of many users and also the emulator" is not helpful at all. A reproducible example definitely helps.
Also, if you believe this is a `frida-compile` issue, you should report it to its repository

**Comment by vfsfitvnm** [comment]
Closing for now!
