### ISSUE TITLE
how to cast argument to a concrete type ,and use it to invoke methods

### ISSUE THREAD

**Issue by andrewpedia** [vfsfitvnm/frida-il2cpp-bridge#378]
I have to invoke a instance method from an interceptor . 
is the args[0] == this?

**Comment by vfsfitvnm** [comment]
If the intercepted method is non-static, then yes https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/2b19c2c731fe0b4cd99ea3816b4931f6203dbe0a/src/il2cpp/structs/method.ts#L329

**Comment by andrewpedia** [comment]
okay,thanks for quick reply.
Now ,how can I use args[0] to invoke a method ,which name is "get_t"?
thanks.

**Comment by vfsfitvnm** [comment]
Please read the wiki or look for other issues/questions, there are plenty of code snippets
