### ISSUE TITLE
Error: abort was called.

### ISSUE THREAD

**Issue by afk-Legacy** [vfsfitvnm/frida-il2cpp-bridge#38]
In the new update, the issue of invoking List.get_Item() seems to have been fixed but now I am facing problem with List.set_Item():

```
    pointInString.implementation = function (format : Il2Cpp.String) : Il2Cpp.String
    {
        
        const PointValue = this.fields.Point.value as Il2Cpp.Object;
        const size = PointValue.methods.get_Count.invoke<number>();

        log("++ Array ++");
        log("Size: " + size.toString());

        PointValue.methods.set_Item.invoke<Int64>(size, 9999); // Code runs normally on commenting this line

        for (let a = 0; a < size; a++)
        {
            const val = PointValue.methods.get_Item.invoke<Int64>(a);    
            log(val.toString())
        }

        log("++ Array ++");
        //log(JSON.stringify(state));
        return this.methods["ToString_"].invoke<Il2Cpp.String>(format);
    }
```
which results in the error:

```
Error: abort was called
    at NativeFunction.<anonymous> (<anonymous>)
    at Il2CppMethod.invokeRaw (../../node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:141:1)
    at Il2CppMethod.<anonymous> (../../node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:149:1)
    at Il2CppObject.pointInString.implementation (index.ts:33:37)
    at InvocationContext.replaceCallback (../../node_modules/frida-il2cpp-bridge/dist/il2cpp/structs/method.js:95:1)
```

**Comment by vfsfitvnm** [comment]
Well, arrays start at 0. 
If the size is 3, the available indexes will be 0, 1 and 2.
You are trying to set an item at index 3 (the fourth one), which throws an exception!

**Comment by afk-Legacy** [comment]
Wow that was the most stupidest thing anyone could have done (not that I have done anything good), I apologize for making a hassle out of nothing.

**Comment by vfsfitvnm** [comment]
Don't worry, I should probably do something to print exceptions nicely. Unfortunately I don't know how to do so yet (besides using `il2cpp_runtime_invoke`).

**Comment by afk-Legacy** [comment]
Yea exceptions would be really nice tbh, I would have tried looking at my code once again if it had an exception like "Index out of bounds" or something similar....
