### ISSUE TITLE
Request `` Addning simple GUI menu like LGL to on and off the options``

### ISSUE THREAD

**Issue by VAROME** [vfsfitvnm/frida-il2cpp-bridge#383]
Request `` Addning simple GUI menu like LGL to on and off the options``
i know some people tried like maars , but their projects does not work on most of the other devices starting from any android less than 13 , and even on 13 too many issues , 
if it came from the source itself it would be unstoppable and awesome , i really hope for it to happen,

**Comment by commonuserlol** [comment]
Hmm you can use `toggle` for that, or do something like
```typescript
menu.button("myhack: OFF", function () {
    // here your code
    this.text = "myhack: ON";
});
```

**Comment by VAROME** [comment]
i dont have any menu for that 

> Hmm you can use `toggle` for that, or do something like
> 
> ```ts
> menu.button("myhack: OFF", function () {
>     // here your code
>     this.text = "myhack: ON";
> });
> ```

**Comment by vfsfitvnm** [comment]
No, this is out of scope!

**Comment by VAROME** [comment]
> No, this is out of scope!

no worries , i made a menu work now, on / off buttons , and functions are done.
