### ISSUE TITLE
how to backtrace

### ISSUE THREAD

**Issue by yujack008** [vfsfitvnm/frida-il2cpp-bridge#392]
i have see https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/10
but no success。
can write a demo to use backtrace.
thank you.

**Comment by vfsfitvnm** [comment]
```ts
Il2Cpp.perform(() => {
    Il2Cpp.backtrace(Backtracer.FUZZY | Backtracer.ACCURATE) // defaults to undefined
        .assemblies(Il2Cpp.domain.assembly("Assembly-CSharp"))
        .and()
        .attach();
});
```

**Comment by yujack008** [comment]
> ```ts
> Il2Cpp.perform(() => {
>     Il2Cpp.backtrace(Backtracer.FUZZY | Backtracer.ACCURATE) // defaults to undefined
>         .assemblies(Il2Cpp.domain.assembly("Assembly-CSharp"))
>         .and()
>         .attach();
> });
> ```

how to get backtrace in  a function call。
like:
```
MyClass.method("MyMethod").implementation = function (...args: any[]) {
    this.backtrace();
    return this.method("MyMethod").invoke(args);
};
```

**Comment by 350030173** [comment]
Il2Cpp.backtrace()
            .verbose(true)
            .assemblies(Il2Cpp.domain.assembly("Assembly-CSharp"))
            .filterClasses(clazz => clazz.name.includes("your class name"))
            .filterMethods(method => method.name.toLowerCase().includes("you method name".toLowerCase()))
            .and()
            .attach();

**Comment by vfsfitvnm** [comment]
More concise:
```ts
Il2Cpp.backtrace()
    .methods(MyClass.method("MyMethod"))
    .and()
    .attach();
```

**Comment by anthonyalayo** [comment]
I don't think this is working. Whenever I try to use IL2Cpp.backtrace() on a function that has it's implementation overwritten, not only do I get no backtrace, but the implementation overwrite is also gone.

**Comment by vfsfitvnm** [comment]
> I don't think this is working. Whenever I try to use IL2Cpp.backtrace() on a function that has it's implementation overwritten, not only do I get no backtrace, but the implementation overwrite is also gone.

The backtracer should not overwrite the original implementation as it relies on `Interceptor.attach` 🤔
