### ISSUE TITLE
how to enumerate instance of certain class?

### ISSUE THREAD

**Issue by abcdefgnihao** [vfsfitvnm/frida-il2cpp-bridge#4]
Mind giving us a sample of how to do so? 
Il2cpp.choose is not available to use now.

**Comment by vfsfitvnm** [comment]
@abcdefgnihao 
Hi!
Sorry, I forgot to update the readme. `choose` and `choose2` have been moved to `Il2Cpp.GC`, so they are `Il2Cpp.GC.choose` and `Il2Cpp.GC.choose2` now!
