### ISSUE TITLE
Create new ulong list Error: abort was called

### ISSUE THREAD

**Issue by thinhbuzz** [vfsfitvnm/frida-il2cpp-bridge#41]
When I try to create new ulong list using below code, When I try to create a new long list using the code below, I can call get_Count method but when I try to add item to list via Add or set_Item methods I always get the error as `Error: abort was called`

Please help me clarify it

```c#
const classes = Il2Cpp.Image.corlib.classes;
const Convert = classes['System.Convert'];
const SystemToUInt64 = classes['System.UInt64'];
const GenericList = classes['System.Collections.Generic.List<T>'];
const SystemToUInt64List = GenericList.inflate(SystemToUInt64);
const instance = Il2Cpp.Object.from(SystemToUInt64List);
// const ulongValue = Convert.methods['ToUInt64_____________'].invoke<any>(Il2Cpp.String.from('1000000000000'));
const ulongValue = new UInt64(1000000000000);
console.log('before', instance.methods.get_Count.invoke(), ulongValue);
// instance.methods.Add.invoke(ulongValue);
instance.methods.set_Item.invoke(0, ulongValue);
console.log('after', instance.methods.get_Count.invoke());
```
![image](https://user-images.githubusercontent.com/8065692/135394800-a032d00b-2047-4740-bd5d-f7fe71933290.png)

**Comment by vfsfitvnm** [comment]
Hi! This is similar to #38.
Your snippet throws the following exception:
```
An error as eccorred; System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00000] in <00000000000000000000000000000000>:0
```
Your list is empty (the count is 0), but you are trying to set the item at index 0.
So, you want to call `Add` instead of `set_Item`:

```ts
instance.methods.Add.invoke(ulongValue);
```

Also, remember to call a constructor (`.ctor`) after allocating the object:
```ts
const instance = Il2Cpp.Object.from(SystemToUInt64List);
instance.methods[".ctor"].invoke();
```

**Comment by thinhbuzz** [comment]
thanks a lot, now I call .ctor and it is working
Before creating this issue I read #38 and tried with Add method but not working.

Thanks again

**Comment by vfsfitvnm** [comment]
@thinhbuzz 
I want to let you know that version `0.6.0` (changes already pushed) will replace `Il2Cpp.Object.from` with `Il2Cpp.Class.alloc` and `Il2Cpp.Class.new`. `new` will automatically call the default constructor (`alloc` just allocates the object).
The script would look like this:
```ts
Il2Cpp.perform(() => {
    const classes = Il2Cpp.Image.corlib.classes;

    const SystemUInt64 = classes["System.UInt64"];
    const GenericList = classes["System.Collections.Generic.List<T>"];
    const SystemUInt64List = GenericList.inflate(SystemUInt64);

    const instance = SystemUInt64List.new(); // <--- change here

    console.log("before", instance.methods.get_Count.invoke());

    instance.methods.Add.invoke(new UInt64(1000000000000));

    console.log("after", instance.methods.get_Count.invoke());
});
```

**Comment by thinhbuzz** [comment]
awesome, thanks for the sweet features.
Beside this issue, do we have any plan for support android emulator? I tried with some games but they don't load libil2cpp so the package can't run

**Comment by vfsfitvnm** [comment]
@thinhbuzz 
You probably want to look at frida's `--realm` flag
