### ISSUE TITLE
Does `decorate` also works for single function?

### ISSUE THREAD

**Issue by commonuserlol** [vfsfitvnm/frida-il2cpp-bridge#413]
Just an internal question, as title says. I saw that it works for interfaces (or how const something = {...} called?), but seems it not work for single function, e.g
```typescript
function asd() {...}
decorate(asd, cache); 
```
decorators can't be applied to single functions (only for class methods/properties) so it will be great to get kinda hack without deps.

**Comment by vfsfitvnm** [comment]
You are correct, you can't decorate a top level function.
You could achieve a similar result by:
```ts
function foo() {
    return 1;
}

function decorate(target) {
    const impl = globalThis[target];
    globalThis[target] = function () {
        return impl() + 1;
    }
}

decorate("foo");
```

**Comment by commonuserlol** [comment]
Now im dealing with applying real decorator to it. My ts knowledge is bad and i didnt found anything in google. For example your `lazy`, how i can apply it to single function? I did workaround for my `cache`
![img](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/111648021/77667119-293b-488b-a081-fe760eae32f5)
 but it requires separate functions. i know that its kinda offtop but any idea?
