### ISSUE TITLE
Did anyone get this?

### ISSUE THREAD

**Issue by Samsli69** [vfsfitvnm/frida-il2cpp-bridge#422]
Hello, I begin with frida-il2cpp-bridge and I don't undertand why I got this message. I followed the MAARS tutorial about frida.

For the Emulator I use AVD - API 30 (Android 11)

The application is running, though.

![Capture d'écran 2023-10-29 193149](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/91052878/5d765cc2-4c7a-47da-8c89-869feaa42c46)

**Comment by Samsli69** [comment]
The app running.

**Comment by ekologic** [comment]
at least share some code maybe?

**Comment by ghost** [comment]
I got the same issue on Memuplay emulator running Android 7.1.2, but when I added `--realm=emulated` flag, I got another error

Il2cpp Bridge Version: 0.9.0

```
PS F:\Mobile-Modding\Frida\il2cpp-livedebug> frida -U -f "com.pockettrend.neomonsters" -l index.js --realm=emulated
     ____
    / _  |   Frida 16.1.4 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to A5010 (id=127.0.0.1:21523)
Spawned `com.pockettrend.neomonsters`. Resuming main thread!
Error: unable to intercept function at 0xc7737b80; please file a bug
    at value (frida/runtime/core.js:371)
    at <anonymous> (utils/native-wait.ts:102)
    at map (native)
    at <anonymous> (utils/native-wait.ts:102)
    at Promise (native)
    at forModule (utils/native-wait.ts:104)
    at initialize (il2cpp/module.ts:16)
    at perform (il2cpp/perform.ts:5)
    at <anonymous> (index.ts:11)
[A5010::com.pockettrend.neomonsters ]-> il2cpp: libil2cpp.so has been loaded, but such event hasn't been detected - please file a bug
ReferenceError: interceptors is not initialized
    at <anonymous> (utils/native-wait.ts:72)
    at apply (native)
    at <anonymous> (frida/runtime/core.js:51)
```

My code

```ts
import "frida-il2cpp-bridge";

Il2Cpp.perform(() => {

    console.log(Il2Cpp.unityVersion);

    Il2Cpp.trace()
        .assemblies(Il2Cpp.domain.assembly("Assembly-CSharp"))
        .and()
        .attach();
});
```

**Comment by VAROME** [comment]
easy , just add emulator check and make it = true ,

**Comment by Samsli69** [comment]
solved thx

**Comment by VAROME** [comment]
solved using another solution or what ?

**Comment by Samsli69** [comment]
Finally, I used my physical device, I did my own searches and it was a frida problem... Emulators are not recommended.
I tried with the boolean emulated realm = true and it worked but I don't want to struggle with problems again so i switched

**Comment by Samsli69** [comment]
I tried with the boolean emulated realm = true and it worked but I don't want to struggle with problems again so i switched

**Comment by VAROME** [comment]
if you dont use / include that , your games wont work on emulators, and some other devices , 
and if you have a menu included like lgl , it will never show ,
