### ISSUE TITLE
il2cpp: couldn't determine the Unity version, please specify it manually

### ISSUE THREAD

**Issue by Den472018** [vfsfitvnm/frida-il2cpp-bridge#427]
Good afternoon, I am using frida-il2cpp-bridge version 0.9.0, there were no problems, but there were problems with one game when I ran the script I received an error with the following content
couldn't determine the Unity version, please specify it manually. In Il2CppInspector I checked the Unity version 2017.3.4f1. I tried to add it manually but it didn't work,
 tell me where exactly the correction needs to be made.
![изображение_2023-11-02_133739793](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/45312820/838c8c4a-ff4f-4814-ac92-69ce2fa9aaca)

**Comment by 350030173** [comment]
[https://github.com/vfsfitvnm/frida-il2cpp-bridge/discussions/390](url)

(gloablThis as any).IL2CPP_UNITY_VERSION = "2019.2.3f1";

Il2Cpp.perform(() => {
    console.log(IL2CPP_UNITY_VERSION); // 2019.2.3f1
});

**Comment by Den472018** [comment]
![изображение_2023-11-04_130151801](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/45312820/43da600d-f60c-4a8f-b248-f5753b32d3b4)

**Comment by Den472018** [comment]
thanks It works
![изображение_2023-11-04_134303466](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/45312820/94fc35a3-aae4-4417-8fa1-9ffd72267f24)
