### ISSUE TITLE
How to get and set  object field

### ISSUE THREAD

**Issue by 2361788963** [vfsfitvnm/frida-il2cpp-bridge#449]
How to get and set  object field
I don't know how it works in frida-il2cpp-bridge.
Why not use il2cpp_field_get_value and il2cpp_field_set_value?

**Comment by vfsfitvnm** [comment]
You can use `Il2Cpp.Field::value`:
```ts
console.log("value is", yourObject.field("fieldName").value);
// change its value
yourObject.field("fieldName").value = 1234;
```

This is how static fields are read (`il2cpp_field_static_get_value`): https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/97ffc512a8a73886fa413716886327c3546c8134/src/structs/field.ts#L78

And this is how instance fields are read (via pointers): https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/97ffc512a8a73886fa413716886327c3546c8134/src/structs/field.ts#L133

**Comment by RevealedSoulEven** [comment]
How to view stack and other types like

<pre>private Stack`1 projectilePool; // 0xb8</pre>

**Comment by RevealedSoulEven** [comment]
Please give a way @vfsfitvnm
