### ISSUE TITLE
Can you tell me how to use the frida-il2cpp-bridge , <3

### ISSUE THREAD

**Issue by bcpx** [vfsfitvnm/frida-il2cpp-bridge#46]
I exec frida -U -f com.xxx  --no-pause -l index.js --runtime=v8 --debug
and it show 
ReferenceError: exports is not defined
    at /index.js:2:23

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Installation
