### ISSUE TITLE
IOS issues, no response after attach

### ISSUE THREAD

**Issue by a2853721** [vfsfitvnm/frida-il2cpp-bridge#47]
![image](https://user-images.githubusercontent.com/40255334/139524633-8a44cd86-744d-4c2a-8918-04ca297318b2.png)
![0CE5A12C7ACCC26AC3E2DCEEAEAF3AF4](https://user-images.githubusercontent.com/40255334/139524642-c7541c71-52fe-4b54-b483-87ed6c15ea1b.jpg)

**Comment by a2853721** [comment]
Do you have any contact information

**Comment by a2853721** [comment]
ios platform, module not Export il2cpp function
Module.findExportByName is NULL, the tool is must faild

**Comment by vfsfitvnm** [comment]
if il2cpp functions are not exported, then the game is not a il2cpp function / export names have been modified (if I understand correclty). In either cases, there's nothing I can do

**Comment by a2853721** [comment]
In all IOS apps, all U3D functions will not be exported

**Comment by vfsfitvnm** [comment]
If `Module.findExportByName(null, "il2cpp_init")` returns `null`, then it's not a Il2Cpp game.
I'm closing this because I don't understand what your problem is...
