### ISSUE TITLE
Exploring a method c# code if possible

### ISSUE THREAD

**Issue by DarkneSsDz** [vfsfitvnm/frida-il2cpp-bridge#476]
is there any way i could dump or extract a static string function code as c# code using this module i got the address and class and name of function but when i try to dig into it i can't is there any workaround for this ?

**Comment by commonuserlol** [comment]
Use disassembler+decompiler with il2cppinspector script

**Comment by vfsfitvnm** [comment]
Not possible - all we have is machine code. You need a disassembler/decompiler.
