### ISSUE TITLE
Any info about Monitor?

### ISSUE THREAD

**Issue by commonuserlol** [vfsfitvnm/frida-il2cpp-bridge#478]
I know only that every object have it as pointer, but nothing about class. Anyone know what it does (.pulse, .wait, etc)?

**Comment by vfsfitvnm** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.threading.monitor?view=net-8.0

**Comment by commonuserlol** [comment]
ohh it's like mutex, thx
