### ISSUE TITLE
Cannot invoke overloaded constructor?

### ISSUE THREAD

**Issue by afk-Legacy** [vfsfitvnm/frida-il2cpp-bridge#48]
Hey, I am trying to invoke a constructor of class but I keep facing issues of invalid paramter length.

![image](https://user-images.githubusercontent.com/83068093/139592027-f98f2d01-5921-4cf4-86af-689a03288988.png)

Here are the constructors of the said class,

![image](https://user-images.githubusercontent.com/83068093/139592110-aa181550-6123-4998-8bf5-41ebff426073.png)

and here is the code being used to access the constructor of said class,

        const UnityCoreModule = Il2Cpp.Domain.assemblies["UnityEngine.CoreModule"].image;
        const UnityImgui =  Il2Cpp.Domain.assemblies["UnityEngine.IMGUIModule"].image; 

        const GUIcontent = UnityImgui.classes["UnityEngine.GUIContent"];
        
        const guicnt = GUIcontent.alloc();
        guicnt.methods[".ctor"].invoke(Il2Cpp.String.from("Hellowwww!"));
        const guicntAsVal = new Il2Cpp.ValueType(guicnt.unbox(), GUIcontent.type);
        
I try to invoke the constructor with string argument but it fails to do so.

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Miscellaneous#overloads-handling

The second constructor key will be `".ctor_"`; `".ctor"` refers to the one that takes no argument
