### ISSUE TITLE
C# typeof operator invocation

### ISSUE THREAD

**Issue by commonuserlol** [vfsfitvnm/frida-il2cpp-bridge#480]
There's method which consumes `System.Type` as argument, when in 'normal' C# it looks like 
```csharp
method(typeof(Klass));
```
Can i somehow invoke typeof operator? (Yes there's another overload with `T method();` and i still remember how to work with it, but i'm interested in typeof)

**Comment by Flechaa** [comment]
For that case you need to somehow get the ``Il2Cpp.Class`` of the the type then inflate it, and invoke the method.
If you have an ``Il2Cpp.Object`` then you can get the class that way or you could simply find the class in the assembly.

**Comment by commonuserlol** [comment]
wdym? I need get type of class, to pass to method (for example: `UnityEngine.Component GetComponent(System.Type type);`)

**Comment by vfsfitvnm** [comment]
```ts
const klass: Il2Cpp.Class = ...
const managedType: Il2Cpp.Object = klass.type.object; // a System.Type
```
