### ISSUE TITLE
How to access enum which is nested in a class?

### ISSUE THREAD

**Issue by etmltg69** [vfsfitvnm/frida-il2cpp-bridge#484]
I have a class which contains a nested enum but I can't access it..

Class looks like following:

```
class A {
   public enum Status {
      Active,
      Disabled
   }
}
```

How to handle that problem? Thanks!

**Comment by vfsfitvnm** [comment]
See https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/219#issuecomment-1237993445 :cheese:
