### ISSUE TITLE
Couldn't obtain the Unity version

### ISSUE THREAD

**Issue by 350030173** [vfsfitvnm/frida-il2cpp-bridge#49]
____                                                                                     
    / _  |   Frida 14.2.2 - A world-class dynamic instrumentation toolkit                     
   | (_| |                                                                                    
    > _  |   Commands:                                                                        
   /_/ |_|       help      -> Displays the help system                                        
   . . . .       object?   -> Display information about 'object'                              
   . . . .       exit/quit -> Exit                                                            
   . . . .                                                                                    
   . . . .   More info at https://www.frida.re/docs/home/                                     
Spawning `com.yunshi.leitingwinter`...                                                        
[il2cpp] Frida's JavaScript runtime is not V8 (--runtime=v8). Proceed with caution.           
Spawned `com.yunshi.leitingwinter`. Resuming main thread!                                     
[MI 8::com.yunshi.leitingwinter]-> **_[il2cpp] Couldn't obtain the Unity version._**                
    at raise (/dumpcs.js:3786)                                                                
    at getUnityVersion (/dumpcs.js:1892)                                                      

the game is:
https://www.taptap.com/app/183733

**Comment by vfsfitvnm** [comment]
I just downloaded that game and I didn't encounter any issue when obtaining the Unity version.
However, that game doesn't export `il2cpp_assembly_get_image`, but this is another "issue"...
