### ISSUE TITLE
what is replacement for IL2CPP.Object::fields that can spit out all fields regardless of class/struct?

### ISSUE THREAD

**Issue by WimpyMistake** [vfsfitvnm/frida-il2cpp-bridge#501]
in the old version 0.6.7, we have this kind of code

```ts
for (const field of object.fields) {
    const fieldValue = field.value as number;
    console.log(fieldValue)
}
```

that eventually can give you values of all fields.

But starting from 0.7.0, the `fields` was removed, and have to explicitly specify the `field name` first.

But my use case is to get all the fields regardless of the Object is class or struct.

For a class I could get by doing this:
```ts
for (const f of object.class.fields) {
    const field = object.field(f.name);
}
```

But if the object is a struct, `object.class` would be `undefined`

I'm using version 0.9.0.

**Comment by vfsfitvnm** [comment]
You could:
```ts
function log(objectOrStruct: Il2Cpp.Object | Il2Cpp.ValueType) {
    const fields = objectOrStruct instanceof Il2Cpp.Object ? objectOrStruct.class.fields 
        : objectOrStruct instanceof Il2Cpp.ValueType ? objectOrStruct.type.class.fields 
        : [];

    for (const field of fields) {
        if (!field.isStatic) {
            const value = objectOrStruct.field(field.name).value;
        }
    }
}
```
Hope it helps :)

(Maybe I could implement a method like `show` for displaying all the field values)
