### ISSUE TITLE
Il2Cpp.dump() encounters an error when running on versions higher than 0.8.5.

### ISSUE THREAD

**Issue by FrothierNine346** [vfsfitvnm/frida-il2cpp-bridge#518]
App package name: com.hypergryph.arknights
Unity Version: 2017.4.39f1
This is the error content
![image](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/79782707/0d450302-38d5-4604-a0b8-e603fd9351ff)

After checking, the problem is caused by the following code
![image](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/79782707/80b7e329-7f02-4f9f-b03d-df6ff3c6a52e)

In version 0.9.0, running succeeds when the specific code section is reverted to the version from 0.8.5.
![image](https://github.com/vfsfitvnm/frida-il2cpp-bridge/assets/79782707/670f961d-2431-4caa-9d24-a25d056de9d0)

**Comment by vfsfitvnm** [comment]
Uhm, unfortunately I cannot reproduce on A11 x86 emulator. What's your platform? And what's your script?

**Comment by FrothierNine346** [comment]
Unfortunately, I am also unable to reproduce it.😂 I used the same platform and script as I remember, but the error did not occur again. I will close this issue since it may not be a bug.
