### ISSUE TITLE
IOS | Support for Apps Without Separate "UnityFramework" File

### ISSUE THREAD

**Issue by Battzz** [vfsfitvnm/frida-il2cpp-bridge#519]
I'm experiencing an issue with the frida-il2cpp-bridge on iOS where it fails to connect to apps that do not have a separate "UnityFramework" file. Instead, these apps integrate the Unity framework into their main executable file. A specific example of this is the game Call of Duty (cod), where the Unity framework is part of the main executable named 'cod' rather than a separate "UnityFramework" file.

Problem:
The current implementation of frida-il2cpp-bridge seems to only connect to a file explicitly named "UnityFramework" by default. This causes issues when working with apps that have the Unity framework integrated into their main executable file, as the bridge does not recognize or connect to the correct process.

if you wanna collaborate, let me know i can provide more information. 
Thank you for this amazing project!

**Comment by vfsfitvnm** [comment]
Hi. The `IL2CPP_UNITY_VERSION` global variable changes the expected module name, as described here:
https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Changelog#v087.

**Comment by Battzz** [comment]
Thanks you. But now facing another problem! 
`il2cpp: couldn't resolve export il2cpp_get_corlib
    at r (/node_modules/frida-il2cpp-bridge/dist/index.js:632)
    at get getCorlib (/node_modules/frida-il2cpp-bridge/dist/index.js:463)
    at call (native)
    at <anonymous> (/node_modules/frida-il2cpp-bridge/dist/index.js:67)
    at initialize (/node_modules/frida-il2cpp-bridge/dist/index.js:1017)`

**Comment by vfsfitvnm** [comment]
Ops, I think you already figured it out, but the correct variable name was `IL2CPP_MODULE_NAME`.
Regarding the new problem, please take a look at similar issues (https://github.com/search?q=repo%3Avfsfitvnm%2Ffrida-il2cpp-bridge+couldn%27t+resolve+export&type=issues) you might find the answer :)

**Comment by Battzz** [comment]
Thank you for solving 👍

**Comment by Leeksov** [comment]
> Спасибо за решение 👍

Hello, can you send your Telegram or something?

i need some help
