### ISSUE TITLE
Issue with Hooking and Creating Vector3 Parameter using frida-il2cpp-bridge

### ISSUE THREAD

**Issue by DarkReunion** [vfsfitvnm/frida-il2cpp-bridge#522]
I have a problem when using frida-il2cpp-bridge with the game. I'm trying to hook a function and create a new Vector3 to pass to it, but the function doesn't execute correctly. When I print the addresses of the original parameter and the one I created, the structures in memory are different, even though they should be the same. The original parameter's address is hard to understand, and I can't find the floating point numbers stored in the Vector3, whereas the ones I created are at offset 0x10.

Here is my code:
`
AssemblyCSharp.class("SpawnerMain").method("SpawnItem").overload("UnityEngine.Vector3", "InvItem", "System.Boolean", "Agent", "System.Boolean").implementation = function(itemPos, item, actionsAfterDrop, owner, streamingSave) {
let v = Vector3.new();
    v.method(".ctor").overload("System.Single", "System.Single").invoke(10086, 13009);
    const result = this.method("SpawnItem").overload("UnityEngine.Vector3", "InvItem", "System.Boolean", "Agent", "System.Boolean").invoke(v, item, actionsAfterDrop, owner, streamingSave);
    return result;
}
`

Other than the field method, all other methods of itemPos are undefined.
Modifying the parameter directly does not solve my issue. I need to be able to call this function from other places.

**Comment by ash47** [comment]
When you create a Vector3, it won't be usable, you need to call `.unbox();` on it to be able to use it in a function / pass it to Unity.

Also, your code is gross / unreadable.

**Comment by DarkReunion** [comment]
> When you create a Vector3, it won't be usable, you need to call `.unbox();` on it to be able to use it in a function / pass it to Unity.
> 
> Also, your code is gross / unreadable.

Thank you very much, it worked. I rarely use GitHub and don't know why the line breaks disappeared when I uploaded the code, so it looks quite messy
