### ISSUE TITLE
Il2Cpp.trace => Error: access violation accessing

### ISSUE THREAD

**Issue by alongsoft2018** [vfsfitvnm/frida-il2cpp-bridge#524]
I am trying to analyze an online mobile game, os: android14  cpu: arm64 

**Il2Cpp.trace(false).methods(traceFunc).and().attach(); // <= false output**

0x010f24cc │ └─Scene::set_NowSceneConfig
0x010f24cc │ ┌─Scene::set_NowSceneConfig
0x010f24cc │ └─Scene::set_NowSceneConfig
0x010f24cc │ ┌─Scene::set_NowSceneConfig
0x010f24cc │ └─Scene::set_NowSceneConfig
0x010f24cc │ ┌─Scene::set_NowSceneConfig
0x010f24cc │ └─Scene::set_NowSceneConfig
0x010f24cc └─Scene::set_NowSceneConfig

HotFix: 0xb4000072a332bac0
                    0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
b4000072a332bac0  c0 f3 3f a3 72 00 00 b4 44 df c3 1b 6f 00 00 b4  ..?.r...D...o...

**Il2Cpp.trace(true).methods(traceFunc).and().attach(); // <= true output**

Error: access violation accessing 0xf7757bb8
    at callback (il2cpp/tracer.ts:300)
Error: access violation accessing 0xf77566a8
    at callback (il2cpp/tracer.ts:300)
Error: access violation accessing 0xf7757bb8
    at callback (il2cpp/tracer.ts:300)
Error: access violation accessing 0xf7757bb8
    at callback (il2cpp/tracer.ts:300)
Error: access violation accessing 0xf7757bb8
    at callback (il2cpp/tracer.ts:300)
Error: access violation accessing 0xf77566a8
    at callback (il2cpp/tracer.ts:300)

**Comment by commonuserlol** [comment]
hey, you can try my fork (in pull requests) which should fix this issue

**Comment by alongsoft2018** [comment]
> hey, you can try my fork (in pull requests) which should fix this issue

Thank you. It's really useful

**Comment by commonuserlol** [comment]
You can close this if it works now.
