### ISSUE TITLE
show Error: expected an integer

### ISSUE THREAD

**Issue by Kn0wns** [vfsfitvnm/frida-il2cpp-bridge#542]
![image](https://github.com/user-attachments/assets/ce75f6bc-35bb-40ff-a946-c920523ab841)

**Comment by Kn0wns** [comment]
The current approach, although effective, appears to be rather cumbersome. I would like to inquire about the reason behind the unavailability of switching to the frida native type for processing.
```js
function arrayToBuffer(array) {
    const buffer = new ArrayBuffer(array.length);
    const view = new Uint8Array(buffer);
    for (let i = 0; i < array.length; i++) {
        view[i] = array[i];
    }
    return buffer;
}

const buff = memoryStream.method("ToArray", 0).invoke();  // System.Byte[] ToArray();
let s = buff.toString().replace('[', "").replace(']', '').split(',')
arrayToBuffer(s)
```

**Comment by Kn0wns** [comment]
The solution has been identified by me.
```js
let bytes = memoryStream.method("ToArray", 0).invoke();  // System.Byte[] ToArray();
let arrayBuffer = ptr(bytes.elements).readByteArray(bytes.length);
```

a new problem has been encountered, and although there is an error message, this does not prevent the script from working properly
![image](https://github.com/user-attachments/assets/80b40bf8-44b6-4545-ba47-fd8e5e6223fd)

There is no error info when commenting `recv.implementation = function (kcp, bytes, len)`

**Comment by vfsfitvnm** [comment]
Unfortunately you have to
```ts
// @ts-ignore <--- this one
recv.implementation = ...
```
(this is a TypeScript thing)

**Comment by Kn0wns** [comment]
`"build": "esbuild --bundle --outfile=hook.js src/main.ts"`
include `xxx.js` in `main.ts`, write hook in `xxx.js`
![image](https://github.com/user-attachments/assets/14e2665c-c580-447a-9cfd-140ae25d66e3)

**Comment by Kn0wns** [comment]
> `"build": "esbuild --bundle --outfile=hook.js src/main.ts"` include `xxx.js` in `main.ts`, write hook in `xxx.js` ![image](https://private-user-images.githubusercontent.com/76414050/361228530-14e2665c-c580-447a-9cfd-140ae25d66e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODY0NTYsIm5iZiI6MTcyNDU4NjE1NiwicGF0aCI6Ii83NjQxNDA1MC8zNjEyMjg1MzAtMTRlMjY2NWMtYzU4MC00NDdhLTljZmQtMTQwYWUyNWQ2NmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDExNDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NTUxZjVkOGQ4YzVmNjY2ZTczNjBjZDY5ZWFmZmE1ZDA4N2JlOTk4ZjIzNDljYTI4ZGRhYjZmYTgyYzVkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUiQjIIY09yGn-Q_b53QRDocTyB_NG0eVcznOepigoQ)

Only recv has error info, but send has no error info

**Comment by Kn0wns** [comment]
Only recv has error info, but send has no error info

**Comment by vfsfitvnm** [comment]
That's a runtime error, somewhere in your code Frida is expecting an integer, but you are passing something else. I guess `ickp_recv` returns an `System.IntXX`, but your implementation is not returning any value

**Comment by Kn0wns** [comment]
Perfect. I thought like frida hook native, don't need to call return

```js
function recv() {
    let KCP = Il2Cpp.domain.assembly("Game.Runtime").image.class('Sining.KCP')
    let recv = KCP.method("ikcp_recv")
    recv.implementation = function (kcp, bytes, len) {
        let arrayBuffer = ptr(bytes.elements).readByteArray(bytes.length);
        let pack = unpack(arrayBuffer);
        let PbHex = pbBuf(bytes, pack);
        log.i(`recv`, `${JSON.stringify(pack)} ${opcodeMapping[pack.OpCode]} ${PbHex}`)
        return this.method("ikcp_recv").invoke(kcp, bytes, len)
    }
}
```
