### ISSUE TITLE
[question] How to call a function with the same method name and parameters

### ISSUE THREAD

**Issue by aiwobazou** [vfsfitvnm/frida-il2cpp-bridge#544]
There are two functions
class A{
System.Void UpdatePosition(DisplayInfoData data);
System.Void UpdatePosition(DisplayInfoData& data); 
}
How should I hook the second function with&and call the original function in the implementation
Using AClass. methods [1] can hook to, but I don't know how to call the original function in the implementation
This. method ("updatePosition"). invoke (data) will point to the first function without&

**Comment by vfsfitvnm** [comment]
The following should work:
```ts
A.method("UpdatePosition").overload("DisplayInfoData&")
```

**Comment by aiwobazou** [comment]
Love you more than heart
