### ISSUE TITLE
How to install and use? 

### ISSUE THREAD

**Issue by AndreiGTA** [vfsfitvnm/frida-il2cpp-bridge#562]
Please tell me how to install and use program frida-il2cpp-bridge

**Comment by thinhbuzz** [comment]
https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Installation

**Comment by AndreiGTA** [comment]
![IMG_20241102_230933.png](https://github.com/user-attachments/assets/3c010843-cc50-4518-afeb-9df0d2f52748)

![IMG_20241102_230915.png](https://github.com/user-attachments/assets/c7703e38-a9af-4f0e-bd43-64b48971b275)

I'm getting errors

**Comment by AndreiGTA** [comment]
> https://github.com/vfsfitvnm/frida-il2cpp-bridge/wiki/Installation

I get errors ![Untitled2.png](https://github.com/user-attachments/assets/3853168d-968f-4392-99d7-930f52a80558)

![Untitled3.png](https://github.com/user-attachments/assets/42507fa8-f1e7-45bf-87b4-a422de05a64c)

![Untitled1.png](https://github.com/user-attachments/assets/061ed79c-acf9-4919-9207-77ff4e86ca58)

![Untitled.png](https://github.com/user-attachments/assets/723ea2a0-8e30-4040-a83a-5c2f4614bb3c)
