### ISSUE TITLE
Modify static field value

### ISSUE THREAD

**Issue by dvgmdvgm** [vfsfitvnm/frida-il2cpp-bridge#57]
Hello.
Try to modify field value: `static System.Int32 _maxTime = 11;`

By following code: 
```
const maxTime: Il2Cpp.Field = Controller.fields["_maxTime"];
(maxTime.value as number) = 4;
```

and get this output:
`Controller._maxTime is a thread static or literal field, its value won't be modified.`

It's possible to modify value in any other way?

**Comment by vfsfitvnm** [comment]
Hi, I couldn't find a way to modify literal values, unfortunately

**Comment by dvgmdvgm** [comment]
Okay)
Thanks to response!))
Issue can be closed i guess

**Comment by vfsfitvnm** [comment]
@dvgmdvgm 
However, you can use a disassembler to see where the literal value actually is (you must decompile a function where it is consumed first - Ghidra would probably assign it a name like `DAT_031efa60`), and then you can use Frida to change its value:
```ts
Il2Cpp.module.base.add(0x031efa60).writeInt(666);
```
I suspect this will be painful!
