### ISSUE TITLE
Il2Cpp.Object.from() is not available

### ISSUE THREAD

**Issue by WimpyMistake** [vfsfitvnm/frida-il2cpp-bridge#61]
I wanted to create my own instance without having to intercept a method. According to this [comment](https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/39#issuecomment-922324104) I could do it via `Il2Cpp.Object.from` but it returns Syntax Error.

**Comment by vfsfitvnm** [comment]
Hi, here I explained what's changed!
https://github.com/vfsfitvnm/frida-il2cpp-bridge/issues/41#issuecomment-932766395

**Comment by WimpyMistake** [comment]
thank you! will try that out.
