### ISSUE TITLE
How to use JS & TS ?

### ISSUE THREAD

**Issue by dvgmdvgm** [vfsfitvnm/frida-il2cpp-bridge#65]
Hello again..
It is possible to use some JS code inside my index.ts ?
I have some default Frida JS code that i cannot replicate via frida-il2cpp-bridge (due some less knowledge reason)
For example i can call some function/methods from other classes to interact with that function but cannot with frida-il2cpp-bridge.
Can we use FridaJS in our *.ts?

**Comment by vfsfitvnm** [comment]
Of course you can, I strongly suggest you to google a little bit about this topic.
