### ISSUE TITLE
How to return null value in implementation?

### ISSUE THREAD

**Issue by thinhbuzz** [vfsfitvnm/frida-il2cpp-bridge#68]
Incase I want to return null value, I need to cast null to any, so we have any shortcut for avoid cast to any?
```typescript
assemblyCsharp['class_name'].methods['method_name'].implementation = () => null as any
````

**Comment by vfsfitvnm** [comment]
Hi, for some reason I didn't add `null` to `Il2Cpp.Method.ReturnType`. However, both `undefined` and `NULL` should be fine, and they don't require any cast

**Comment by thinhbuzz** [comment]
I will try with undefined.
Do you have paypal or something like that? I want to send you some :coffee:. :wink:

**Comment by vfsfitvnm** [comment]
Nah man, I'm good thanks! Send them to [frida](https://frida.re/contact/) instead :)

Ps - can we close this?
