### ISSUE TITLE
method Error 7023

### ISSUE THREAD

**Issue by Coinswang** [vfsfitvnm/frida-il2cpp-bridge#7]
I npm install  this project
then those method have error:

object.ts: 
   /**
     * See {@link _Il2CppClass.methods} for an example.
     * @return Its methods.
     */
    @cache get **_methods_**() {
        return this.class.methods[filterAndMap](
            method => method.isInstance,
            method => method.asHeld(this.handle)
        );
    }

method.ts:
    /** @internal */
    @shouldBeInstance(true)
    **_asHeld_**(holder: NativePointer) {
        const invoke = this._invoke.bind(this, holder);
        return {
            invoke<T extends AllowedType>(...parameters: AllowedType[]) {
                return invoke(...parameters) as T;
            }
        } as Invokable;
    }

7023    Error  '{0}' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

**Comment by vfsfitvnm** [comment]
@Coinswang 
Hi, I cannot reproduce this issue.
Could you tell me which TS version are you using?
