### ISSUE TITLE
intercept 你删除了？

### ISSUE THREAD

**Issue by zbx911** [vfsfitvnm/frida-il2cpp-bridge#70]
function hook_xluaL_loadbuffer(){
    const image_name = "Assembly-CSharp"
    const class_name = "XLua.LuaDLL.Lua"
    const method_name = "xluaL_loadbuffer"

    const coreModule = Il2Cpp.Domain.assemblies[image_name].image;
    const tmpClass = coreModule.classes[class_name];
    const method= tmpClass.methods[method_name]
    // @ts-ignore
    console.log("[+] hook_xluaL_loadbuffer")
    method.intercept({
        // @ts-ignore
        onEnter(instance, parameters) {
           var buf=parameters["buff"].value as number ;
           var file=""+parameters["name"].value+"";
           var size=parameters["size"].value as number;
           var data=ptr(buf).add(0x20).readByteArray(size)
            // @ts-ignore
            console.log("加载lua脚本:",file)
           send({
               "function":method_name,
               "file":file
           },data)

        },
    });

}

**Comment by vfsfitvnm** [comment]
I don't want to be rude or whatsoever, I really don't understand what you are trying to say in your recent issues.
I know there's a language barrier, but please take more effort in writing them... my English is far from perfect but it's comprehensible I guess, and that's enough.

How can I help you if the title is in Chinese, you provide no context of what you are trying to do, you are not saying what doesn't work and you paste a badly formatted code snippet - which uses a very old version of this library?
