### ISSUE TITLE
Getting the class or classname of the object using NativePointer

### ISSUE THREAD

**Issue by wildsheepz** [vfsfitvnm/frida-il2cpp-bridge#75]
Hi, is there a way to get the classname or class of the object of the NativePointer?

**Comment by vfsfitvnm** [comment]
hi, what do you mean by `the object of the NativePointer`?

**Comment by wildsheepz** [comment]
I am trying to achieve something similar to detailed trace in the wiki, because sometimes native functions are called with polymorphic objects, I'd like to figure out what the object is in the onEnter callback function

**Comment by vfsfitvnm** [comment]
The `Il2Cpp.Object` you get via `this` inside the `implementation` callback is automatically casted to match the declaring class of the intercepted method. However, the cast is artifical, so if you'd like to undo this behavior, you could create a new object like this:
```ts
// this is a Il2Cpp.Object, probably downcasted
const originalThis = new Il2Cpp.Object(this.handle);
// now originalThis.class is "correct"
```

If you have a raw `NativePointer` (e.g. `Interceptor.attach`'s `.onEnter`), you could create a `Il2Cpp.Object` as well.

**Comment by wildsheepz** [comment]
That works very nicely! Thanks!
