### ISSUE TITLE
How to use Il2Cpp.Reference ?

### ISSUE THREAD

**Issue by kruvcraft21** [vfsfitvnm/frida-il2cpp-bridge#88]
Hi , I came across a method using a reference 
``` cs
System.Void Method(System.Single& p1);
```
and I wondered how to use Il2Cpp.Reference
I wrote this code:
```ts
Assembly["Class"].methods["Method"].implementation = function (p1: Il2Cpp.Reference<number>) : void {
     p1.value = 0
}
```
And I got an error:
`Error: expected a pointer`

then I rewrote the code like this:
```ts
Assembly["Class"].methods["Method"].implementation = function (p1: Il2Cpp.Reference) : void {
     p1.value = ptr(0)
}
```
and there was no mistake, how do I write the number 1 , for example?

**Comment by vfsfitvnm** [comment]
This is a bug; the problem occurs here: https://github.com/vfsfitvnm/frida-il2cpp-bridge/blob/6e05f47a70d10754c806fd23391d47383b8039ef/src/il2cpp/utils.ts#L56

It always expects a pointer. I don't even  remember why I added that check, so it will take a bit to figure out if it's safe to remove.
Meanwhile, you could do something along these lines:
```ts
p1.handle.writeFloat(1);
```

**Comment by kruvcraft21** [comment]
ok, then I should probably close issue? if it's a bug

**Comment by vfsfitvnm** [comment]
Nah, it will close itself once I push the fix

**Comment by vfsfitvnm** [comment]
Hmm, I just deleted those lines in 0.6.8, let's see if it leads to a regression
