### ISSUE TITLE
The untiy version that is 2021.2

### ISSUE THREAD

**Issue by 350030173** [vfsfitvnm/frida-il2cpp-bridge#89]
The untiy version that is 2021.2.x

the game url：https://play.google.com/store/apps/details?id=com.car.games.drifter.driving.simulator

**Comment by vfsfitvnm** [comment]
Thanks, the update is easy, however the trick I use to determine the Unity version doesn't work anymore (don't worry, I already found a workaround).
Could you find another application with Unity version 2021.2.x? So I can determine if it's a common trait since that version

**Comment by vfsfitvnm** [comment]
Fixed in 0.7.1
