### ISSUE TITLE
some class can not show  the fields value

### ISSUE THREAD

**Issue by 350030173** [vfsfitvnm/frida-il2cpp-bridge#96]
**the game url:**
https://apkpure.com/cn/rocket-punch/com.Highscoregames.Drawrocket

```
import "frida-il2cpp-bridge";

Il2Cpp.perform(() =>
{

    const SystemString = Il2Cpp.Image.corlib.class("System.String");
    var AssemblyCSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;

    //public class GameManager : MonoBehaviourSingleton<GameManager>
    //public class AppLovinManager : MonoBehaviourSingleton<AppLovinManager>
    var AppLovinManager = AssemblyCSharp.class("AppLovinManager");

    //can show the fields value in the SystemString class
    //can not show the fields value in the GameManager class and AppLovinManager class
    Il2Cpp.GC.choose(AppLovinManager).forEach((instance) =>
    {
        //var dynamicFields = instance.fields; //**int version 0.6.6 can get all fields in the class ,now can not get the fields**
        var dynamicFields = instance.class.fields;//should modify it this way to get it ?
        console.log("\n" + dynamicFields);
        for (var i in dynamicFields)
        {
            console.log("\n" + dynamicFields[i].name + "; // " + dynamicFields[i].offset, "\x1b[32m" + dynamicFields[i].value + "\x1B[0m");
        }
    });
});
```

**Comment by vfsfitvnm** [comment]
Hi, `Il2Cpp.Object::fields` was removed because it looked useless.
You can now do the same thing like this:
```ts
import "frida-il2cpp-bridge";

Il2Cpp.perform(() => {
    const AssemblyCSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;

    const AppLovinManager = AssemblyCSharp.class("AppLovinManager");

    Il2Cpp.GC.choose(AppLovinManager).forEach(instance => {
        for (const field of AppLovinManager.fields) {
            if (field.isStatic) continue;

            console.log(`${field} \x1b[32m${instance.field(field.name).value}\x1B[0m`);
        }
    });
});
```

**Comment by 350030173** [comment]
> Hi, `Il2Cpp.Object::fields` was removed because it looked useless. You can now do the same thing like this:
> 
> ```ts
> import "frida-il2cpp-bridge";
> 
> Il2Cpp.perform(() => {
>     const AssemblyCSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;
> 
>     const AppLovinManager = AssemblyCSharp.class("AppLovinManager");
> 
>     Il2Cpp.GC.choose(AppLovinManager).forEach(instance => {
>         for (const field of AppLovinManager.fields) {
>             if (field.isStatic) continue;
> 
>             console.log(`${field} \x1b[32m${instance.field(field.name).value}\x1B[0m`);
>         }
>     });
> });
> ```

thank you ,but still have bug for other game.
**the game url :**
https://apkpure.com/cn/mischief-to-couple/com.tygame.game19

**my code:**
```
Il2Cpp.perform(() =>
{
    const AssemblyCSharp = Il2Cpp.Domain.assembly("Assembly-CSharp").image;

    //public class SetUpPanelCtrl : SXUICtrlTemplate<SetUpPanel>
    const SetUpPanelCtrl = AssemblyCSharp.class("SetUpPanelCtrl");
    const myfields = SetUpPanelCtrl.fields;
    for (const i in myfields)
    {
        if (myfields[i].isStatic)
        {
            console.log("\n" + myfields[i], "\x1b[32m" + myfields[i].value + "\x1B[0m");
        }
    }

    Il2Cpp.GC.choose(SetUpPanelCtrl).forEach((instance) =>
    {
        for (const field of SetUpPanelCtrl.fields) 
        {
            if (field.isStatic) continue;

            console.log(`${field} \x1b[32m${instance.field(field.name).value}\x1B[0m`);
        }
    });
});
```
output:
**TypeError: not a function**



**and if the class name is the following:**
the game url:
https://apkpure.com/cn/kung-fu-z/com.tinytitanstudios.kfz
```
// Namespace: 
public class GameCode.GameInst // TypeDefIndex: 3766
```
the Namespace is empty, and the class name have "." in the class
output:
**il2cpp: couldn't find class GameCode.GameInst in Assembly-CSharp.dll, did you mean GameCode?**

**Comment by vfsfitvnm** [comment]
`GameInst` is a nested class.
```ts
.class("GameCode").nested("GameInst");
```

**Comment by vfsfitvnm** [comment]
The other one:
```ts
for (const i in myfields)
```
Replace `in` with `of`

**Comment by 350030173** [comment]
> 



> The other one:
> 
> ```ts
> for (const i in myfields)
> ```
> 
> Replace `in` with `of`

sorry，it same
the game url:
https://apkpure.com/cn/mischief-to-couple-11/com.tyou.qinglv11
![image](https://user-images.githubusercontent.com/20263746/154401076-02f00784-2f9b-42c1-818d-9dad3f2eb47a.png)

**Comment by vfsfitvnm** [comment]
Ok, the stacktrace shows something different.

**Comment by vfsfitvnm** [comment]
@350030173 That game somehow stripped the `UnityEngine.Application::get_unityVersion` method.
I won't restore the old Unity version detection method because is very easy to make it fail (this is also an issue you reported, #89).

It's easier to detect the Unity version by yourself and then:
```ts
import "frida-il2cpp-bridge";

Il2Cpp.perform(() => {
    Reflect.defineProperty(Il2Cpp, "unityVersion", { value: "2018.3.11f1" });
    
    // ...
});

```

**Comment by 350030173** [comment]
> @350030173 That game somehow stripped the `UnityEngine.Application::get_unityVersion` method. I won't restore the old Unity version detection method because is very easy to make it fail (this is also an issue you reported, #89).
> 
> It's easier to detect the Unity version by yourself and then:
> 
> ```ts
> import "frida-il2cpp-bridge";
> 
> Il2Cpp.perform(() => {
>     Reflect.defineProperty(Il2Cpp, "unityVersion", { value: "2018.3.11f1" });
>     
>     // ...
> });
> ```

sorry , i come again 
the game url:
https://apkpure.com/cn/super-stickman-dragon-warriors/com.stickmanwarriors.stickmandragon.stickfighter
![image](https://user-images.githubusercontent.com/20263746/154892561-ef777664-e6c2-4316-8a01-78e9bcd462e7.png)

**Comment by vfsfitvnm** [comment]
@350030173 
You have to figure it out yourself, all I see is you are not attached to Il2Cpp when invoking `showAllClassFieldValue`.
You can try:
```ts
(globalThis as any).showAllClassFieldValue = function() {
    Il2Cpp.perform(showAllClassFieldValue);
}
```
