### ISSUE TITLE
Timeout was reached

### ISSUE THREAD

**Issue by kruvcraft21** [vfsfitvnm/frida-il2cpp-bridge#99]
Hi,

when I use this code via frida-inject : 

```ts
import "frida-il2cpp-bridge";

Il2Cpp.perform(() => {
	Il2Cpp.dump()
})
```
I get this error during the dump : 
```
...
[il2cpp] dumping Assembly-CSharp...
Timeout was reached
```
I think it's important to add that the `Timeout was reached` error can occur at any point in the dump.

are there ways to solve this problem ?

**Comment by vfsfitvnm** [comment]
Hi, since version [0.7.1](https://github.com/vfsfitvnm/frida-il2cpp-bridge#071) the dump is made by javascript code; it's slow and that's why the "timeout was reached" error occurs. However you can just ignore it, it's harmless

**Comment by kruvcraft21** [comment]
yes, you're right, I thought the dump stops at this point, but I tested and I was able to get the dump.
